{
 "title": "Openshift Logging Collection",
 "tags": [ "logging" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "repeat": "datasource",
   "panels": [
    {
     "title": "Total log bytes collected last 24h",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(sum_over_time(vector_processed_bytes_total{component_kind=\"source\"}[24h]))",
       "legendFormat": "{{component_type}}"
      }
     ]
    },
    {
     "title": "Total log bytes sent last 24h",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(sum_over_time(vector_component_sent_bytes_total{component_kind=\"sink\", component_type!=\"prometheus_exporter\"}[24h]))",
       "legendFormat": "{{component_type}}"
      }
     ]
    },
    {
     "title": "Rate log bytes collected last 24h",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (component_type)(sum_over_time(vector_processed_bytes_total{component_kind=\"source\"}[24h]))",
       "legendFormat": "{{component_type}}"
      }
     ]
    },
    {
     "title": "Rate log bytes sent last 24h",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(component_type)(sum_over_time(vector_component_sent_bytes_total{component_kind=\"sink\", component_type!=\"prometheus_exporter\"}[24h]))",
       "legendFormat": "{{component_type}}"
      }
     ]
    },
    {
     "title": "Total errors last 60m",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(irate(vector_component_errors_total[1h]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Outputs",
   "type": "row",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "repeat": "datasource",
   "panels": [
    {
     "title": "Rate log bytes sent per output",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by (component_id, component_type)(irate(vector_component_sent_bytes_total{component_kind=\"sink\", component_type!=\"prometheus_exporter\"}[5m]))",
       "legendFormat": "id:{{component_id}} type:{{component_type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Produced Logs",
   "type": "row",
   "gridPos": { "h": 7, "w": 8, "x": 24, "y": 1 },
   "panels": [
    {
     "title": "Top producing containers",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "format": "bytes",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(10, round(rate(log_logged_bytes_total[5m])))",
       "legendFormat": "{{exported_namespace}}/{{podname}}/{{containername}}"
      }
     ]
    },
    {
     "title": "Top producing containers in last 24 hours",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "topk(10, sum(increase(log_logged_bytes_total[24h])) by (exported_namespace,  podname, containername))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Machine",
   "type": "row",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "repeat": "datasource",
   "panels": [
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum by(node,namespace,pod)(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{container='collector'})",
       "legendFormat": "{{node}}/{{namespace}}/{{pod}}"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by(node,namespace,pod)(node_namespace_pod_container:container_memory_rss{container=\"collector\"})",
       "legendFormat": "{{node}}/{{namespace}}/{{pod}}"
      }
     ]
    },
    {
     "title": "Running containers",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (node)(kubelet_running_containers{container_state=\"running\"})",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Open files for container logs",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(hostname,namespace,pod)(vector_open_files{component_kind=\"source\", component_type=\"kubernetes_logs\"})",
       "legendFormat": "{{hostname}}/{{namespace}}/{{pod}}"
      }
     ]
    }
   ]
  }
 ]
}