apiVersion: "observability.openshift.io/v1"
kind: ClusterLogForwarder
metadata:
  name: mine
  namespace: openshift-logging 
spec:
  serviceAccount:
    name: foo
  filters:
    - name: mydrop
      type: drop
      drop:
        - test:
          - field: .kubernetes.labels."foo-bar/baz"
            matches: avalue
  inputs:
    - name: audit
      type: audit
      audit:
        sources:
          - openshiftAPI
  outputs:
    - name: myhttp
      type: http
      http:
        url: http://http-receiver.openshift-logging.svc:8090
  pipelines:
   - name: application-logs 
     inputRefs: 
     - audit
     filterRefs:
     - mydrop
     outputRefs:
     - myhttp
