apiVersion: observability.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: my-collector
spec:
  serviceAccount:
    name: test-sa
  outputs:
    - name: lokistack-out
      type: lokiStack
      lokiStack:
        target:
          name: lokistack-test
          namespace: openshift-logging
        authentication:
          token:
            from: serviceAccount
      tls:
        insecureSkipVerify: true
  pipelines:
    - name: all-logs
      inputRefs:
        - application
        - audit
        - infrastructure
      outputRefs:
        - lokistack-out
