apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

patches:
- patch: |-
    - op: replace
      path: /spec/pipelines/0/outputRefs/0
      value: http-receiver
    - op: add
      path: /spec/outputs
      value:
      - name: http-receiver
        type: http
        http:
          url: http://http-receiver.openshift-logging.svc:8090
  target:
    kind: ClusterLogForwarder