= Cluster Log Forwarding

The link:../reference/operator/api_observability_v1.adoc[ClusterLogForwarder] custom resource is the API for specifying the collection and forwarding
of cluster logs (e.g. application, infrastructure, audit).  This API is part of the *observability.openshift.io* group and replaces the similarly named
link:https://github.com/openshift/cluster-logging-operator/blob/release-5.9/docs/reference/operator/api.adoc[resource] that was part of the *logging.openshift.io* group

== High-level Features

* ClusterLogForwarder instances in any namespace with any name
* Log source collection authorized/restricted by cluster RBAC
* Isolated collector deployments per ClusterLogForwarder
* Explicit configuration of secrets and configmaps for outputs

NOTE: Vector is the only collector implementation

=== Prerequisites

The following is required in order for the operator to deploy a log collector
in response to an instance of ClusterLogForwarder:

* an existing serviceaccount for use by the collector and referenced in the ClusterLogForwarder spec
* the serviceaccount bound to one or more cluster roles deployed by the operator: collect-application-logs, collect-infrastructure-logs, collect-audit-logs
* a serviceaccount token if required by any outputs
* users who create or update the ClusterLogForwarder must have the `use` RBAC verb on the referenced ServiceAccount (enforced by a ValidatingAdmissionPolicy installed by the operator). See link:serviceaccount-authorization.adoc[ServiceAccount usage authorization] for details and examples.

NOTE: Each input type defined in the ClusterLogForwarder spec must have a corresponding rolebinding for the spec to be valid

=== Restrictions

Fields are validated by the API server upon admission or update and provide immediate feedback to the user.  Additional validation
is performed post creation and is reflected in status.

When `spec.serviceAccount.name` is set, the API server also verifies that the requesting user may `use` that ServiceAccount.  Denied requests fail before the resource is stored.  Deleting a ClusterLogForwarder is not subject to this check.

NOTE: The status section of the ClusterLogForwarder may provide useful information when collectors do not deploy as expected

=== Modifying the Collector Resources and Scheduling

Some log forwarding deployments may require the administrator to modify the resources or scheduling of the collector.  This
is accomplished by modifying the following fields:

* spec.managementState
* spec.collector
** Currently supported:
... link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.19/html/building_applications/quotas#quotas-resources-managed_quotas-setting-per-project[spec.collector.resources]
... link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.19/html/nodes/controlling-pod-placement-onto-nodes-scheduling#nodes-scheduler-node-selectors[spec.collector.nodeSelector]
... link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.19/html/nodes/controlling-pod-placement-onto-nodes-scheduling#nodes-scheduler-taints-tolerations-about_nodes-scheduler-taints-tolerations[spec.collector.tolerations]
... link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.19/html/nodes/controlling-pod-placement-onto-nodes-scheduling#nodes-scheduler-node-affinity[spec.collector.affinity]