run:
  timeout: 5m
linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - errcheck
    - exportloopref
    - gocyclo
    - gofmt
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - staticcheck
    - structcheck
    - typecheck
    - unconvert
    - unused
    - varcheck

# Consider enabling these, some cleanup required:
# dupl: Tool for code clone detection [fast: true, auto-fix: false]
# gocritic: Provides many diagnostics that check for bugs, performance and style issues. [fast: true, auto-fix: false]
# goimports: Goimports does everything that gofmt does. Additionally it checks unused imports [fast: true, auto-fix: true]
# gomnd: An analyzer to detect magic numbers. [fast: true, auto-fix: false]
# stylecheck: Stylecheck is a replacement for golint [fast: true, auto-fix: false]
# whitespace: Tool for detection of leading and trailing whitespace [fast: true, auto-fix: true]
