# This dockerfile combines the elasticsearch operator source
# with the cluster logging operator source so we can use all the
# test scripts to deploy the elasticsearch operator and then
# test the clusterlogging operator
FROM registry.svc.ci.openshift.org/ocp/4.6:elasticsearch-operator-src
ADD . /go/src/github.com/openshift/cluster-logging-operator
WORKDIR /go/src/github.com/openshift/cluster-logging-operator
