diff --git a/Dockerfile b/Dockerfile.local
index 596e84be..8772b35b 100644
--- a/Dockerfile
+++ b/Dockerfile.local
@@ -1,4 +1,4 @@
-FROM registry.svc.ci.openshift.org/ocp/builder:rhel-8-golang-1.15-openshift-4.7 AS builder
+FROM registry.svc.ci.openshift.org/openshift/release:golang-1.15 as builder
 WORKDIR /go/src/github.com/openshift/cluster-logging-operator
 
 # COPY steps are in the reverse order of frequency of change
@@ -16,9 +16,7 @@ COPY pkg ./pkg
 
 RUN make build
 
-FROM registry.svc.ci.openshift.org/ocp/4.7:cli as origincli
-
-FROM registry.svc.ci.openshift.org/ocp/4.7:base
+FROM centos:centos8 as centos
 RUN INSTALL_PKGS=" \
       rsync \
       xz \
@@ -34,7 +32,6 @@ COPY --from=builder /go/src/github.com/openshift/cluster-logging-operator/files/
 COPY --from=builder /go/src/github.com/openshift/cluster-logging-operator/manifests /manifests
 RUN rm /manifests/art.yaml
 
-COPY --from=origincli /usr/bin/oc /usr/bin/
 COPY --from=builder /go/src/github.com/openshift/cluster-logging-operator/must-gather/collection-scripts/* /usr/bin/
 
 WORKDIR /usr/bin
