= Cluster Logging Operator

An operator to support log collection and forwarding on OpenShift clusters. Cluster logging configuration information
is found in the link:./docs/administration/configuration.md[configuration] documentation.  This
operator is solely responsible for configuring log collection and forwarding.  It works in conjunction
with the deployment of a LokiStack via the https://github.com/openshift/loki-operator[loki-operator].  The loki-operator is responsible for log storage.

== Overview

The Cluster Logging Operator (CLO) provides a set of APIs to control collection and forwarding of logs from
all pods and nodes in a cluster. This includes _application_ logs (from regular
pods), _infrastructure_ logs (from system pods and node logs), and _audit_ logs
(special node logs with legal/security implications)

The CLO deploys:

* A log collector/forwarder (current implimentation is https://vector.dev/[Vector])

and relies upon:

* Loki as a log storage engine
* The https://github.com/rhobs/observability-operator[cluster-obervability-operator] (COO) to provide a visualization plugin to the Openshift console.

The goal is to _abstract_ away the deployment and configuration of these technologies behind APIs so that:

* A user has a simplified logging experience
* A user has less to learn
* Technologies can be replaced in the future without affecting the user experience.

The CLO can also _forward_ logs over multiple protocols, to multiple types of log stores, on- or off-cluster

The CLO _owns_ the following APIs:

* ClusterLogForwarder: Configure forwarding of logs to external sources
* LogFileMetricsExporter: Configure deployment of a component to monitor the volume of logs generated by container workloads

== Getting Started ==
* To install a released version of cluster logging see the https://docs.redhat.com/en/documentation/red_hat_openshift_logging/6.3/html/installing_logging/index[Openshift Logging Documentation]
* To experiment or contribute to the development of cluster logging, see the link:docs/contributing/README.adoc[hacking] and link:docs/contributing/REVIEW.adoc[review] documentation
* To debug the cluster logging stack, see link:./must-gather/README.md[README.md]
* To find currently known Cluster Logging Operator issues with work-arounds, see the link:docs/administration/troubleshooting.md[Troubleshooting] guide.
