[transforms.pipeline_mypipeline_my_drop_filter_0]
type = "filter"
inputs = ["input_app_in_viaq_logtype","input_infra_in_viaq_logtype"]
condition = '''
!((!match(to_string(.kubernetes.namespace_name) ?? "", r'very-important') && match(to_string(.level) ?? "", r'warning|error|critical')) || (match(to_string(.message) ?? "", r'foobar') && !match(to_string(.kubernetes.namespace_labels."test-dashes/slashes") ?? "", r'true')))
'''