apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: clusterlogging-shared-config
  namespace: openshift-config-managed
rules:
- apiGroups: [""]
  resources:
  - configmaps
  verbs:
    - get
    - create
    - update
    - delete
