---
# This is a patch for the operator deployment deployment YAML ../../manager/manager.yaml
# It modifies the RELATED_IMAGE environment variables.
# Do not change anything other than the `value` fields in the `env` section.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-logging-operator
spec:
  template:
    spec:
      containers:
        - name: cluster-logging-operator
          imagePullPolicy: IfNotPresent
          env:
            # EDIT HERE: change the 'value' fields to the related images you want to use.
            - name: RELATED_IMAGE_VECTOR
              value: quay.io/openshift-logging/vector:6.0
            - name: RELATED_IMAGE_FLUENTD
              value: quay.io/openshift-logging/fluentd:5.9.0
            - name: RELATED_IMAGE_LOG_FILE_METRIC_EXPORTER
              value: quay.io/openshift-logging/log-file-metric-exporter:1.0
            - name: OPERATOR_NAME
              value: cluster-logging-operator
