module _ // Auto generated by https://github.com/bwplotka/bingo. DO NOT EDIT

go 1.14

require (
	github.com/openshift/origin v4.1.0+incompatible // indirect
	github.com/openshift/release v0.0.0-20220531132329-92dee95b5da2 // tools/junitreport
)
