module _ // Auto generated by https://github.com/bwplotka/bingo. DO NOT EDIT

go 1.14

require (
	github.com/openshift/origin v4.1.0+incompatible // indirect
	github.com/openshift/release v0.0.0-20201103150245-a5287ef1495b // tools/junitreport
)
