module _ // Auto generated by https://github.com/bwplotka/bingo. DO NOT EDIT

go 1.25.0

toolchain go1.25.0

require github.com/openshift/release v0.0.0-20220531132329-92dee95b5da2 // tools/junitreport
