module _ // Auto generated by https://github.com/bwplotka/bingo. DO NOT EDIT

go 1.15

replace github.com/Azure/go-autorest => github.com/Azure/go-autorest v13.3.2+incompatible

replace github.com/mattn/go-sqlite3 => github.com/mattn/go-sqlite3 v1.10.0

replace golang.org/x/text => golang.org/x/text v0.3.3

replace k8s.io/client-go => k8s.io/client-go v0.18.2

require github.com/operator-framework/operator-sdk v1.2.0 // cmd/operator-sdk
