apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    control-plane: cluster-logging-operator
  name: cluster-logging-operator-metrics-monitor
spec:
  endpoints:
  - port: https-metrics
    scheme: https
    tlsConfig:
      caFile: /etc/prometheus/configmaps/serving-certs-ca-bundle/service-ca.crt
      serverName: cluster-logging-operator-metrics.openshift-logging.svc
  namespaceSelector: {}
  selector:
    matchLabels:
      name: cluster-logging-operator
