apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    name: cluster-logging-operator
  name: cluster-logging-operator-metrics
spec:
  ports:
  - name: http-metrics
    port: 8686
    protocol: TCP
    targetPort: 8686
  selector:
    name: cluster-logging-operator
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
