apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: cluster-logging-write-audit-logs
rules:
- apiGroups:
  - loki.grafana.com
  resourceNames:
  - logs
  resources:
  - audit
  verbs:
  - create
