apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: cluster-logging-operator-telemetry
spec:
  groups:
  - name: telemetry.rules
    rules:
    - expr: sum by (resource_namespace, version) (log_forwarder_pipelines)
      record: openshift_logging:log_forwarder_pipelines:sum
    - expr: count by (resource_namespace, version) (log_forwarder_pipelines)
      record: openshift_logging:log_forwarders:sum
    - expr: sum by (resource_namespace, version, input) (log_forwarder_input_type)
      record: openshift_logging:log_forwarder_input_type:sum
    - expr: sum by (resource_namespace, version, output) (log_forwarder_output_type)
      record: openshift_logging:log_forwarder_output_type:sum
    - expr: sum by(namespace) (rate(vector_component_received_bytes_total{component_kind="source",
        component_type!="internal_metrics"}[5m]))
      record: openshift_logging:vector_component_received_bytes_total:rate5m
