apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  labels:
    name: cluster-logging-operator
  name: log-collector-privileged
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - log-collector-scc
  resources:
  - securitycontextconstraints
  verbs:
  - use
