apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

patches:
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/0/value
      value: http-receiver.openshift-logging.svc.cluster.local
    - op: replace
      path: /spec/template/spec/containers/0/env/1/value
      value: "8090"
  target:
    kind: Deployment