apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: cluster-logging-operator-validating-webhook
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: cluster-logging-operator-webhook-service
      namespace: system
      path: /validate-observability-openshift-io-v1-clusterlogforwarder
  failurePolicy: Fail
  name: vclusterlogforwarder.observability.openshift.io
  rules:
  - apiGroups:
    - observability.openshift.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - clusterlogforwarders
  sideEffects: None
