[sources.input_myreceiver]
type = "syslog"
address = "[::]:12345"
mode = "tcp"

[sources.input_myreceiver.tls]
enabled = true
key_file = "/var/run/ocp-collector/secrets/instance-myreceiver/tls.key"
crt_file = "/var/run/ocp-collector/config/instance-myreceiver/my.crt"
ca_file = "/var/run/ocp-collector/config/instance-myreceiver/ca.crt"

[transforms.input_myreceiver_meta]
type = "remap"
inputs = ["input_myreceiver"]
source = '''
  . = {"_internal": {"structured": .}}
  ._internal.log_source = "node"
  ._internal.log_type = "infrastructure"
  ._internal.openshift = { "cluster_id": "${OPENSHIFT_CLUSTER_ID:-}"}
  ._internal.level = ._internal.severity || "unknown"
'''