# Logs from kubernetes audit
[sources.input_myaudit_kube]
type = "file"
include = ["/var/log/kube-apiserver/audit.log"]
host_key = "hostname"
glob_minimum_cooldown_ms = 15000
ignore_older_secs = 3600
max_read_bytes = 3145728
rotate_wait_ms = 5000

[transforms.input_myaudit_kube_viaq]
type = "remap"
inputs = ["input_myaudit_kube"]
source = '''
  .openshift.cluster_id = "${OPENSHIFT_CLUSTER_ID:-}"
  .tag = ".k8s-audit.log"
  . = merge(., parse_json!(string!(.message))) ?? .
  del(.message)
  .k8s_audit_level = .level
'''

# Set log_type
[transforms.input_myaudit_viaq_logtype]
type = "remap"
inputs = ["input_myaudit_kube_viaq"]
source = '''
  .log_type = "audit"
  .hostname = get_env_var("VECTOR_SELF_NODE_NAME") ?? ""
  ts = del(.timestamp); if !exists(."@timestamp") {."@timestamp" = ts}
'''