package fluent

//JsonJavaStackTrace - sample of Java stack trace in JSON format
const JsonJavaStackTrace = "{\"instant\":{\"epochSecond\":1617711572,\"nanoOfSecond\":619500000},\"thread\":\"main\"," +
	"\"level\":\"ERROR\",\"loggerName\":\"App\",\"message\":\"trace\",\"thrown\":{\"commonElementCount\":0," +
	"\"localizedMessage\":\"/ by zero\",\"message\":\"/ by zero\",\"name\":\"java.lang.ArithmeticException\"," +
	"\"extendedStackTrace\":[{\"class\":\"App\",\"method\":\"main\",\"file\":\"App.java\",\"line\":15," +
	"\"exact\":true,\"location\":\"classes/\",\"version\":\"?\"},{\"class\":\"jdk.internal.reflect.NativeMethodAccessorImpl\"," +
	"\"method\":\"invoke0\",\"file\":\"NativeMethodAccessorImpl.java\",\"line\":-2,\"exact\":false,\"location\":\"?\"," +
	"\"version\":\"?\"},{\"class\":\"jdk.internal.reflect.NativeMethodAccessorImpl\",\"method\":\"invoke\"," +
	"\"file\":\"NativeMethodAccessorImpl.java\",\"line\":62,\"exact\":false,\"location\":\"?\",\"version\":\"?\"}," +
	"{\"class\":\"jdk.internal.reflect.DelegatingMethodAccessorImpl\",\"method\":\"invoke\",\"file\":\"DelegatingMethodAccessorImpl.java\"," +
	"\"line\":43,\"exact\":false,\"location\":\"?\",\"version\":\"?\"},{\"class\":\"java.lang.reflect.Method\"," +
	"\"method\":\"invoke\",\"file\":\"Method.java\",\"line\":566,\"exact\":false,\"location\":\"?\",\"version\":\"?\"}," +
	"{\"class\":\"com.intellij.rt.execution.application.AppMainV2\",\"method\":\"main\",\"file\":\"AppMainV2.java\"," +
	"\"line\":131,\"exact\":true,\"location\":\"idea_rt.jar\",\"version\":\"?\"},{\"class\":\"App\",\"method\":\"main\"," +
	"\"file\":\"App.java\",\"line\":15,\"exact\":true,\"location\":\"classes/\",\"version\":\"?\"},{\"class\":" +
	"\"jdk.internal.reflect.NativeMethodAccessorImpl\",\"method\":\"invoke0\",\"file\":\"NativeMethodAccessorImpl.java\"," +
	"\"line\":-2,\"exact\":false,\"location\":\"?\",\"version\":\"?\"},{\"class\":\"jdk.internal.reflect.NativeMethodAccessorImpl\"," +
	"\"method\":\"invoke\",\"file\":\"NativeMethodAccessorImpl.java\",\"line\":62,\"exact\":false,\"location\":\"?\"," +
	"\"version\":\"?\"},{\"class\":\"jdk.internal.reflect.DelegatingMethodAccessorImpl\",\"method\":\"invoke\"," +
	"\"file\":\"DelegatingMethodAccessorImpl.java\",\"line\":43,\"exact\":false,\"location\":\"?\",\"version\":\"?\"}," +
	"{\"class\":\"java.lang.reflect.Method\",\"method\":\"invoke\",\"file\":\"Method.java\",\"line\":566,\"exact\":false," +
	"\"location\":\"?\",\"version\":\"?\"},{\"class\":\"com.intellij.rt.execution.application.AppMainV2\",\"method\":\"main\"," +
	"\"file\":\"AppMainV2.java\",\"line\":131,\"exact\":true,\"location\":\"idea_rt.jar\",\"version\":\"?\"},{\"class\":\"App\"," +
	"\"method\":\"main\",\"file\":\"App.java\",\"line\":15,\"exact\":true,\"location\":\"classes/\",\"version\":\"?\"}," +
	"{\"class\":\"jdk.internal.reflect.NativeMethodAccessorImpl\",\"method\":\"invoke0\",\"file\":\"NativeMethodAccessorImpl.java\"," +
	"\"line\":-2,\"exact\":false,\"location\":\"?\",\"version\":\"?\"},{\"class\":\"jdk.internal.reflect.NativeMethodAccessorImpl\"," +
	"\"method\":\"invoke\",\"file\":\"NativeMethodAccessorImpl.java\",\"line\":62,\"exact\":false,\"location\":\"?\"," +
	"\"version\":\"?\"},{\"class\":\"jdk.internal.reflect.DelegatingMethodAccessorImpl\",\"method\":\"invoke\"," +
	"\"file\":\"DelegatingMethodAccessorImpl.java\",\"line\":43,\"exact\":false,\"location\":\"?\",\"version\":\"?\"}," +
	"{\"class\":\"java.lang.reflect.Method\",\"method\":\"invoke\",\"file\":\"Method.java\",\"line\":566,\"exact\":false," +
	"\"location\":\"?\",\"version\":\"?\"},{\"class\":\"com.intellij.rt.execution.application.AppMainV2\",\"method\":\"main\"," +
	"\"file\":\"AppMainV2.java\",\"line\":131,\"exact\":true,\"location\":\"idea_rt.jar\",\"version\":\"?\"},{\"class\":\"App\"," +
	"\"method\":\"main\",\"file\":\"App.java\",\"line\":15,\"exact\":true,\"location\":\"classes/\",\"version\":\"?\"}," +
	"{\"class\":\"jdk.internal.reflect.NativeMethodAccessorImpl\",\"method\":\"invoke0\",\"file\":\"NativeMethodAccessorImpl.java\"," +
	"\"line\":-2,\"exact\":false,\"location\":\"?\",\"version\":\"?\"},{\"class\":\"jdk.internal.reflect.NativeMethodAccessorImpl\"," +
	"\"method\":\"invoke\",\"file\":\"NativeMethodAccessorImpl.java\",\"line\":62,\"exact\":false,\"location\":\"?\",\"version\":\"?\"}," +
	"{\"class\":\"jdk.internal.reflect.DelegatingMethodAccessorImpl\",\"method\":\"invoke\",\"file\":\"DelegatingMethodAccessorImpl.java\"," +
	"\"line\":43,\"exact\":false,\"location\":\"?\",\"version\":\"?\"},{\"class\":\"java.lang.reflect.Method\",\"method\":\"invoke\"," +
	"\"file\":\"Method.java\",\"line\":566,\"exact\":false,\"location\":\"?\",\"version\":\"?\"},{\"class\":\"com.intellij.rt.execution.application.AppMainV2\"," +
	"\"method\":\"main\",\"file\":\"AppMainV2.java\",\"line\":131,\"exact\":true,\"location\":\"idea_rt.jar\",\"version\":\"?\"},{\"class\":\"App\"," +
	"\"method\":\"main\",\"file\":\"App.java\",\"line\":15,\"exact\":true,\"location\":\"classes/\",\"version\":\"?\"}," +
	"{\"class\":\"jdk.internal.reflect.NativeMethodAccessorImpl\",\"method\":\"invoke0\",\"file\":\"NativeMethodAccessorImpl.java\"," +
	"\"line\":-2,\"exact\":false,\"location\":\"?\",\"version\":\"?\"},{\"class\":\"jdk.internal.reflect.NativeMethodAccessorImpl\"," +
	"\"method\":\"invoke\",\"file\":\"NativeMethodAccessorImpl.java\",\"line\":62,\"exact\":false,\"location\":\"?\",\"version\":\"?\"}," +
	"{\"class\":\"jdk.internal.reflect.DelegatingMethodAccessorImpl\",\"method\":\"invoke\",\"file\":\"DelegatingMethodAccessorImpl.java\"," +
	"\"line\":43,\"exact\":false,\"location\":\"?\",\"version\":\"?\"},{\"class\":\"java.lang.reflect.Method\",\"method\":\"invoke\"," +
	"\"file\":\"Method.java\",\"line\":566,\"exact\":false,\"location\":\"?\",\"version\":\"?\"},{\"class\":\"com.intellij.rt.execution.application.AppMainV2\"," +
	"\"method\":\"main\",\"file\":\"AppMainV2.java\",\"line\":131,\"exact\":true,\"location\":\"idea_rt.jar\",\"version\":\"?\"}," +
	"{\"class\":\"App\",\"method\":\"main\",\"file\":\"App.java\",\"line\":15,\"exact\":true,\"location\":\"classes/\",\"version\":\"?\"}," +
	"{\"class\":\"jdk.internal.reflect.NativeMethodAccessorImpl\",\"method\":\"invoke0\",\"file\":\"NativeMethodAccessorImpl.java\"," +
	"\"line\":-2,\"exact\":false,\"location\":\"?\",\"version\":\"?\"},{\"class\":\"jdk.internal.reflect.NativeMethodAccessorImpl\"," +
	"\"method\":\"invoke\",\"file\":\"NativeMethodAccessorImpl.java\",\"line\":62,\"exact\":false,\"location\":\"?\",\"version\":\"?\"}," +
	"{\"class\":\"jdk.internal.reflect.DelegatingMethodAccessorImpl\",\"method\":\"invoke\",\"file\":\"DelegatingMethodAccessorImpl.java\"," +
	"\"line\":43,\"exact\":false,\"location\":\"?\",\"version\":\"?\"},{\"class\":\"java.lang.reflect.Method\",\"method\":\"invoke\"," +
	"\"file\":\"Method.java\",\"line\":566,\"exact\":false,\"location\":\"?\",\"version\":\"?\"},{\"class\":\"com.intellij.rt.execution.application.AppMainV2\"," +
	"\"method\":\"main\",\"file\":\"AppMainV2.java\",\"line\":131,\"exact\":true,\"location\":\"idea_rt.jar\",\"version\":\"?\"},{\"class\":\"App\"," +
	"\"method\":\"main\",\"file\":\"App.java\",\"line\":15,\"exact\":true,\"location\":\"classes/\",\"version\":\"?\"}," +
	"{\"class\":\"jdk.internal.reflect.NativeMethodAccessorImpl\",\"method\":\"invoke0\",\"file\":\"NativeMethodAccessorImpl.java\"," +
	"\"line\":-2,\"exact\":false,\"location\":\"?\",\"version\":\"?\"},{\"class\":\"jdk.internal.reflect.NativeMethodAccessorImpl\"," +
	"\"method\":\"invoke\",\"file\":\"NativeMethodAccessorImpl.java\",\"line\":62,\"exact\":false,\"location\":\"?\",\"version\":\"?\"}," +
	"{\"class\":\"jdk.internal.reflect.DelegatingMethodAccessorImpl\",\"method\":\"invoke\",\"file\":\"DelegatingMethodAccessorImpl.java\"," +
	"\"line\":43,\"exact\":false,\"location\":\"?\",\"version\":\"?\"},{\"class\":\"java.lang.reflect.Method\",\"method\":\"invoke\"," +
	"\"file\":\"Method.java\",\"line\":566,\"exact\":false,\"location\":\"?\",\"version\":\"?\"},{\"class\":\"com.intellij.rt.execution.application.AppMainV2\"," +
	"\"method\":\"main\",\"file\":\"AppMainV2.java\",\"line\":131,\"exact\":true,\"location\":\"idea_rt.jar\",\"version\":\"?\"}," +
	"{\"class\":\"App\",\"method\":\"main\",\"file\":\"App.java\",\"line\":15,\"exact\":true,\"location\":\"classes/\",\"version\":\"?\"}," +
	"{\"class\":\"jdk.internal.reflect.NativeMethodAccessorImpl\",\"method\":\"invoke0\",\"file\":\"NativeMethodAccessorImpl.java\",\"line\":-2," +
	"\"exact\":false,\"location\":\"?\",\"version\":\"?\"},{\"class\":\"jdk.internal.reflect.NativeMethodAccessorImpl\",\"method\":\"invoke\"," +
	"\"file\":\"NativeMethodAccessorImpl.java\",\"line\":62,\"exact\":false,\"location\":\"?\",\"version\":\"?\"},{\"class\":" +
	"\"jdk.internal.reflect.DelegatingMethodAccessorImpl\",\"method\":\"invoke\",\"file\":\"DelegatingMethodAccessorImpl.java\",\"line\":43," +
	"\"exact\":false,\"location\":\"?\",\"version\":\"?\"},{\"class\":\"java.lang.reflect.Method\",\"method\":\"invoke\",\"file\":\"Method.java\"," +
	"\"line\":566,\"exact\":false,\"location\":\"?\",\"version\":\"?\"},{\"class\":\"com.intellij.rt.execution.application.AppMainV2\",\"method\":\"main\"," +
	"\"file\":\"AppMainV2.java\",\"line\":131,\"exact\":true,\"location\":\"idea_rt.jar\",\"version\":\"?\"},{\"class\":\"App\",\"method\":\"main\"," +
	"\"file\":\"App.java\",\"line\":15,\"exact\":true,\"location\":\"classes/\",\"version\":\"?\"},{\"class\":\"jdk.internal.reflect.NativeMethodAccessorImpl\"," +
	"\"method\":\"invoke0\",\"file\":\"NativeMethodAccessorImpl.java\",\"line\":-2,\"exact\":false,\"location\":\"?\",\"version\":\"?\"}," +
	"{\"class\":\"jdk.internal.reflect.NativeMethodAccessorImpl\",\"method\":\"invoke\",\"file\":\"NativeMethodAccessorImpl.java\",\"line\":62," +
	"\"exact\":false,\"location\":\"?\",\"version\":\"?\"},{\"class\":\"jdk.internal.reflect.DelegatingMethodAccessorImpl\",\"method\":\"invoke\",\"file\":\"DelegatingMethodAccessorImpl.java\"," +
	"\"line\":43,\"exact\":false,\"location\":\"?\",\"version\":\"?\"},{\"class\":\"java.lang.reflect.Method\",\"method\":\"invoke\"," +
	"\"file\":\"Method.java\",\"line\":566,\"exact\":false,\"location\":\"?\",\"version\":\"?\"},{\"class\":\"com.intellij.rt.execution.application.AppMainV2\"," +
	"\"method\":\"main\",\"file\":\"AppMainV2.java\",\"line\":131,\"exact\":true,\"location\":\"idea_rt.jar\",\"version\":\"?\"}," +
	"{\"class\":\"App\",\"method\":\"main\",\"file\":\"App.java\",\"line\":15,\"exact\":true,\"location\":\"classes/\"," +
	"\"version\":\"?\"},{\"class\":\"jdk.internal.reflect.NativeMethodAccessorImpl\",\"method\":\"invoke0\",\"file\":\"NativeMethodAccessorImpl.java\"," +
	"\"line\":-2,\"exact\":false,\"location\":\"?\",\"version\":\"?\"},{\"class\":\"jdk.internal.reflect.NativeMethodAccessorImpl\",\"method\":\"invoke\"," +
	"\"file\":\"NativeMethodAccessorImpl.java\",\"line\":62,\"exact\":false,\"location\":\"?\",\"version\":\"?\"}," +
	"{\"class\":\"jdk.internal.reflect.DelegatingMethodAccessorImpl\",\"method\":\"invoke\",\"file\":\"DelegatingMethodAccessorImpl.java\"," +
	"\"line\":43,\"exact\":false,\"location\":\"?\",\"version\":\"?\"},{\"class\":\"java.lang.reflect.Method\",\"method\":\"invoke\"," +
	"\"file\":\"Method.java\",\"line\":566,\"exact\":false,\"location\":\"?\",\"version\":\"?\"},{\"class\":\"com.intellij.rt.execution.application.AppMainV2\"," +
	"\"method\":\"main\",\"file\":\"AppMainV2.java\",\"line\":131,\"exact\":true,\"location\":\"idea_rt.jar\",\"version\":\"?\"}," +
	"{\"class\":\"App\",\"method\":\"main\",\"file\":\"App.java\",\"line\":15,\"exact\":true,\"location\":\"classes/\"," +
	"\"version\":\"?\"},{\"class\":\"jdk.internal.reflect.NativeMethodAccessorImpl\",\"method\":\"invoke0\",\"file\":\"NativeMethodAccessorImpl.java\"," +
	"\"line\":-2,\"exact\":false,\"location\":\"?\",\"version\":\"?\"},{\"class\":\"jdk.internal.reflect.NativeMethodAccessorImpl\"," +
	"\"method\":\"invoke\",\"file\":\"NativeMethodAccessorImpl.java\",\"line\":62,\"exact\":false,\"location\":\"?\",\"version\":\"?\"}," +
	"{\"class\":\"jdk.internal.reflect.DelegatingMethodAccessorImpl\",\"method\":\"invoke\",\"file\":\"DelegatingMethodAccessorImpl.java\"," +
	"\"line\":43,\"exact\":false,\"location\":\"?\",\"version\":\"?\"},{\"class\":\"java.lang.reflect.Method\",\"method\":\"invoke\"," +
	"\"file\":\"Method.java\",\"line\":566,\"exact\":false,\"location\":\"?\",\"version\":\"?\"},{\"class\":\"com.intellij.rt.execution.application.AppMainV2\"," +
	"\"method\":\"main\",\"file\":\"AppMainV2.java\",\"line\":131,\"exact\":true,\"location\":\"idea_rt.jar\",\"version\":\"?\"},{\"class\":\"App\"," +
	"\"method\":\"main\",\"file\":\"App.java\",\"line\":15,\"exact\":true,\"location\":\"classes/\",\"version\":\"?\"}," +
	"{\"class\":\"jdk.internal.reflect.NativeMethodAccessorImpl\",\"method\":\"invoke0\",\"file\":\"NativeMethodAccessorImpl.java\"," +
	"\"line\":-2,\"exact\":false,\"location\":\"?\",\"version\":\"?\"},{\"class\":\"jdk.internal.reflect.NativeMethodAccessorImpl\"," +
	"\"method\":\"invoke\",\"file\":\"NativeMethodAccessorImpl.java\",\"line\":62,\"exact\":false,\"location\":\"?\",\"version\":\"?\"}," +
	"{\"class\":\"jdk.internal.reflect.DelegatingMethodAccessorImpl\",\"method\":\"invoke\",\"file\":\"DelegatingMethodAccessorImpl.java\"," +
	"\"line\":43,\"exact\":false,\"location\":\"?\",\"version\":\"?\"},{\"class\":\"java.lang.reflect.Method\",\"method\":\"invoke\"," +
	"\"file\":\"Method.java\",\"line\":566,\"exact\":false,\"location\":\"?\",\"version\":\"?\"},{\"class\":\"com.intellij.rt.execution.application.AppMainV2\"," +
	"\"method\":\"main\",\"file\":\"AppMainV2.java\",\"line\":131,\"exact\":true,\"location\":\"idea_rt.jar\",\"version\":\"?\"}," +
	"{\"class\":\"App\",\"method\":\"main\",\"file\":\"App.java\",\"line\":15,\"exact\":true,\"location\":\"classes/\",\"version\":\"?\"}," +
	"{\"class\":\"jdk.internal.reflect.NativeMethodAccessorImpl\",\"method\":\"invoke0\",\"file\":\"NativeMethodAccessorImpl.java\",\"line\":-2," +
	"\"exact\":false,\"location\":\"?\",\"version\":\"?\"},{\"class\":\"jdk.internal.reflect.NativeMethodAccessorImpl\",\"method\":\"invoke\"," +
	"\"file\":\"NativeMethodAccessorImpl.java\",\"line\":62,\"exact\":false,\"location\":\"?\",\"version\":\"?\"}," +
	"{\"class\":\"jdk.internal.reflect.DelegatingMethodAccessorImpl\",\"method\":\"invoke\",\"file\":\"DelegatingMethodAccessorImpl.java\",\"line\":43," +
	"\"exact\":false,\"location\":\"?\",\"version\":\"?\"},{\"class\":\"java.lang.reflect.Method\",\"method\":\"invoke\"," +
	"\"file\":\"Method.java\",\"line\":566,\"exact\":false,\"location\":\"?\",\"version\":\"?\"},{\"class\":\"com.intellij.rt.execution.application.AppMainV2\"," +
	"\"method\":\"main\",\"file\":\"AppMainV2.java\",\"line\":131,\"exact\":true,\"location\":\"idea_rt.jar\",\"version\":\"?\"},{\"class\":\"App\"," +
	"\"method\":\"main\",\"file\":\"App.java\",\"line\":15,\"exact\":true,\"location\":\"classes/\",\"version\":\"?\"}," +
	"{\"class\":\"jdk.internal.reflect.NativeMethodAccessorImpl\",\"method\":\"invoke0\",\"file\":\"NativeMethodAccessorImpl.java\"," +
	"\"line\":-2,\"exact\":false,\"location\":\"?\",\"version\":\"?\"},{\"class\":\"jdk.internal.reflect.NativeMethodAccessorImpl\"," +
	"\"method\":\"invoke\",\"file\":\"NativeMethodAccessorImpl.java\",\"line\":62,\"exact\":false,\"location\":\"?\",\"version\":\"?\"}," +
	"{\"class\":\"jdk.internal.reflect.DelegatingMethodAccessorImpl\",\"method\":\"invoke\"," +
	"\"file\":\"DelegatingMethodAccessorImpl.java\",\"line\":43,\"exact\":false,\"location\":\"?\",\"version\":\"?\"}," +
	"{\"class\":\"java.lang.reflect.Method\",\"method\":\"invoke\",\"file\":\"Method.java\",\"line\":566,\"exact\":false," +
	"\"location\":\"?\",\"version\":\"?\"},{\"class\":\"com.intellij.rt.execution.application.AppMainV2\",\"method\":\"main\"," +
	"\"file\":\"AppMainV2.java\",\"line\":131,\"exact\":true,\"location\":\"idea_rt.jar\",\"version\":\"?\"},{\"class\":\"App\"," +
	"\"method\":\"main\",\"file\":\"App.java\",\"line\":15,\"exact\":true,\"location\":\"classes/\",\"version\":\"?\"}," +
	"{\"class\":\"jdk.internal.reflect.NativeMethodAccessorImpl\",\"method\":\"invoke0\",\"file\":\"NativeMethodAccessorImpl.java\"," +
	"\"line\":-2,\"exact\":false,\"location\":\"?\",\"version\":\"?\"},{\"class\":\"jdk.internal.reflect.NativeMethodAccessorImpl\"," +
	"\"method\":\"invoke\",\"file\":\"NativeMethodAccessorImpl.java\",\"line\":62,\"exact\":false,\"location\":\"?\",\"version\":\"?\"}," +
	"{\"class\":\"jdk.internal.reflect.DelegatingMethodAccessorImpl\",\"method\":\"invoke\",\"file\":\"DelegatingMethodAccessorImpl.java\"," +
	"\"line\":43,\"exact\":false,\"location\":\"?\",\"version\":\"?\"},{\"class\":\"java.lang.reflect.Method\",\"method\":\"invoke\"," +
	"\"file\":\"Method.java\",\"line\":566,\"exact\":false,\"location\":\"?\",\"version\":\"?\"},{\"class\":" +
	"\"com.intellij.rt.execution.application.AppMainV2\",\"method\":\"main\",\"file\":\"AppMainV2.java\",\"line\":131," +
	"\"exact\":true,\"location\":\"idea_rt.jar\",\"version\":\"?\"},{\"class\":\"App\",\"method\":\"main\",\"file\":\"App.java\"," +
	"\"line\":15,\"exact\":true,\"location\":\"classes/\",\"version\":\"?\"},{\"class\":\"jdk.internal.reflect.NativeMethodAccessorImpl\"," +
	"\"method\":\"invoke0\",\"file\":\"NativeMethodAccessorImpl.java\",\"line\":-2,\"exact\":false,\"location\":\"?\",\"version\":\"?\"}," +
	"{\"class\":\"jdk.internal.reflect.NativeMethodAccessorImpl\",\"method\":\"invoke\",\"file\":\"NativeMethodAccessorImpl.java\"," +
	"\"line\":62,\"exact\":false,\"location\":\"?\",\"version\":\"?\"},{\"class\":\"jdk.internal.reflect.DelegatingMethodAccessorImpl\"," +
	"\"method\":\"invoke\",\"file\":\"DelegatingMethodAccessorImpl.java\",\"line\":43,\"exact\":false,\"location\":\"?\",\"version\":\"?\"}," +
	"{\"class\":\"java.lang.reflect.Method\",\"method\":\"invoke\",\"file\":\"Method.java\",\"line\":566,\"exact\":false,\"location\":\"?\"," +
	"\"version\":\"?\"},{\"class\":\"com.intellij.rt.execution.application.AppMainV2\",\"method\":\"main\",\"file\":\"AppMainV2.java\"," +
	"\"line\":131,\"exact\":true,\"location\":\"idea_rt.jar\",\"version\":\"?\"},{\"class\":\"App\",\"method\":\"main\",\"file\":\"App.java\"," +
	"\"line\":15,\"exact\":true,\"location\":\"classes/\",\"version\":\"?\"},{\"class\":\"jdk.internal.reflect.NativeMethodAccessorImpl\"," +
	"\"method\":\"invoke0\",\"file\":\"NativeMethodAccessorImpl.java\",\"line\":-2,\"exact\":false,\"location\":\"?\",\"version\":\"?\"}," +
	"{\"class\":\"jdk.internal.reflect.NativeMethodAccessorImpl\",\"method\":\"invoke\",\"file\":\"NativeMethodAccessorImpl.java\"," +
	"\"line\":62,\"exact\":false,\"location\":\"?\",\"version\":\"?\"},{\"class\":\"jdk.internal.reflect.DelegatingMethodAccessorImpl\"," +
	"\"method\":\"invoke\",\"file\":\"DelegatingMethodAccessorImpl.java\",\"line\":43,\"exact\":false,\"location\":\"?\",\"version\":\"?\"}," +
	"{\"class\":\"java.lang.reflect.Method\",\"method\":\"invoke\",\"file\":\"Method.java\",\"line\":566,\"exact\":false,\"location\":\"?\"," +
	"\"version\":\"?\"},{\"class\":\"com.intellij.rt.execution.application.AppMainV2\",\"method\":\"main\",\"file\":\"AppMainV2.java\",\"line\":131," +
	"\"exact\":true,\"location\":\"idea_rt.jar\",\"version\":\"?\"},{\"class\":\"App\",\"method\":\"main\",\"file\":\"App.java\",\"line\":15,\"exact\":true," +
	"\"location\":\"classes/\",\"version\":\"?\"},{\"class\":\"jdk.internal.reflect.NativeMethodAccessorImpl\",\"method\":\"invoke0\"," +
	"\"file\":\"NativeMethodAccessorImpl.java\",\"line\":-2,\"exact\":false,\"location\":\"?\",\"version\":\"?\"},{\"class\":" +
	"\"jdk.internal.reflect.NativeMethodAccessorImpl\",\"method\":\"invoke\",\"file\":\"NativeMethodAccessorImpl.java\",\"line\":62," +
	"\"exact\":false,\"location\":\"?\",\"version\":\"?\"},{\"class\":\"jdk.internal.reflect.DelegatingMethodAccessorImpl\"," +
	"\"method\":\"invoke\",\"file\":\"DelegatingMethodAccessorImpl.java\",\"line\":43,\"exact\":false,\"location\":\"?\"," +
	"\"version\":\"?\"},{\"class\":\"java.lang.reflect.Method\",\"method\":\"invoke\",\"file\":\"Method.java\",\"line\":566," +
	"\"exact\":false,\"location\":\"?\",\"version\":\"?\"},{\"class\":\"com.intellij.rt.execution.application.AppMainV2\"," +
	"\"method\":\"main\",\"file\":\"AppMainV2.java\",\"line\":131,\"exact\":true,\"location\":\"idea_rt.jar\",\"version\":\"?\"}," +
	"{\"class\":\"App\",\"method\":\"main\",\"file\":\"App.java\",\"line\":15,\"exact\":true,\"location\":\"classes/\",\"version\":\"?\"}," +
	"{\"class\":\"jdk.internal.reflect.NativeMethodAccessorImpl\",\"method\":\"invoke0\",\"file\":\"NativeMethodAccessorImpl.java\",\"line\":-2," +
	"\"exact\":false,\"location\":\"?\",\"version\":\"?\"}," +
	"{\"class\":\"jdk.internal.reflect.NativeMethodAccessorImpl\",\"method\":\"invoke\",\"file\":\"NativeMethodAccessorImpl.java\"," +
	"\"line\":62,\"exact\":false,\"location\":\"?\",\"version\":\"?\"},{\"class\":\"jdk.internal.reflect.DelegatingMethodAccessorImpl\"," +
	"\"method\":\"invoke\",\"file\":\"DelegatingMethodAccessorImpl.java\",\"line\":43,\"exact\":false,\"location\":\"?\",\"version\":\"?\"}," +
	"{\"class\":\"java.lang.reflect.Method\",\"method\":\"invoke\",\"file\":\"Method.java\",\"line\":566,\"exact\":false,\"location\":\"?\"," +
	"\"version\":\"?\"},{\"class\":\"com.intellij.rt.execution.application.AppMainV2\",\"method\":\"main\",\"file\":\"AppMainV2.java\"," +
	"\"line\":131,\"exact\":true,\"location\":\"idea_rt.jar\",\"version\":\"?\"},{\"class\":\"App\",\"method\":\"main\",\"file\":\"App.java\"," +
	"\"line\":15,\"exact\":true,\"location\":\"classes/\",\"version\":\"?\"},{\"class\":\"jdk.internal.reflect.NativeMethodAccessorImpl\"," +
	"\"method\":\"invoke0\",\"file\":\"NativeMethodAccessorImpl.java\",\"line\":-2,\"exact\":false,\"location\":\"?\",\"version\":\"?\"}," +
	"{\"class\":\"jdk.internal.reflect.NativeMethodAccessorImpl\",\"method\":\"invoke\",\"file\":\"NativeMethodAccessorImpl.java\",\"line\":62," +
	"\"exact\":false,\"location\":\"?\",\"version\":\"?\"},{\"class\":\"jdk.internal.reflect.DelegatingMethodAccessorImpl\",\"method\":\"invoke\"," +
	"\"file\":\"DelegatingMethodAccessorImpl.java\",\"line\":43,\"exact\":false,\"location\":\"?\",\"version\":\"?\"},{\"class\":\"java.lang.reflect.Method\"," +
	"\"method\":\"invoke\",\"file\":\"Method.java\",\"line\":566,\"exact\":false,\"location\":\"?\",\"version\":\"?\"}," +
	"{\"class\":\"com.intellij.rt.execution.application.AppMainV2\",\"method\":\"main\",\"file\":\"AppMainV2.java\"," +
	"\"line\":131,\"exact\":true,\"location\":\"idea_rt.jar\",\"version\":\"?\"},{\"class\":\"App\",\"method\":\"main\"," +
	"\"file\":\"App.java\",\"line\":15,\"exact\":true,\"location\":\"classes/\",\"version\":\"?\"},{\"class\":\"jdk.internal.reflect.NativeMethodAccessorImpl\"," +
	"\"method\":\"invoke0\",\"file\":\"NativeMethodAccessorImpl.java\",\"line\":-2,\"exact\":false,\"location\":\"?\",\"version\":\"?\"}," +
	"{\"class\":\"jdk.internal.reflect.NativeMethodAccessorImpl\",\"method\":\"invoke\",\"file\":\"NativeMethodAccessorImpl.java\",\"line\":62," +
	"\"exact\":false,\"location\":\"?\",\"version\":\"?\"},{\"class\":\"jdk.internal.reflect.DelegatingMethodAccessorImpl\",\"method\":\"invoke\"," +
	"\"file\":\"DelegatingMethodAccessorImpl.java\",\"line\":43,\"exact\":false,\"location\":\"?\",\"version\":\"?\"},{\"class\":\"java.lang.reflect.Method\"," +
	"\"method\":\"invoke\",\"file\":\"Method.java\",\"line\":566,\"exact\":false,\"location\":\"?\",\"version\":\"?\"}," +
	"{\"class\":\"com.intellij.rt.execution.application.AppMainV2\",\"method\":\"main\",\"file\":\"AppMainV2.java\",\"line\":131," +
	"\"exact\":true,\"location\":\"idea_rt.jar\",\"version\":\"?\"},{\"class\":\"App\",\"method\":\"main\",\"file\":\"App.java\"," +
	"\"line\":15,\"exact\":true,\"location\":\"classes/\",\"version\":\"?\"},{\"class\":\"jdk.internal.reflect.NativeMethodAccessorImpl\",\"method\":\"invoke0\"," +
	"\"file\":\"NativeMethodAccessorImpl.java\",\"line\":-2,\"exact\":false,\"location\":\"?\",\"version\":\"?\"},{\"class\":\"jdk.internal.reflect.NativeMethodAccessorImpl\",\"method\":\"invoke\"," +
	"\"file\":\"NativeMethodAccessorImpl.java\",\"line\":62,\"exact\":false,\"location\":\"?\",\"version\":\"?\"},{\"class\":\"jdk.internal.reflect.DelegatingMethodAccessorImpl\"," +
	"\"method\":\"invoke\",\"file\":\"DelegatingMethodAccessorImpl.java\",\"line\":43,\"exact\":false,\"location\":\"?\"," +
	"\"version\":\"?\"},{\"class\":\"java.lang.reflect.Method\",\"method\":\"invoke\",\"file\":\"Method.java\",\"line\":566,\"exact\":false," +
	"\"location\":\"?\",\"version\":\"?\"},{\"class\":\"com.intellij.rt.execution.application.AppMainV2\",\"method\":\"main\",\"file\":\"AppMainV2.java\"," +
	"\"line\":131,\"exact\":true,\"location\":\"idea_rt.jar\",\"version\":\"?\"},{\"class\":\"App\",\"method\":\"main\",\"file\":\"App.java\",\"line\":15," +
	"\"exact\":true,\"location\":\"classes/\",\"version\":\"?\"},{\"class\":\"jdk.internal.reflect.NativeMethodAccessorImpl\",\"method\":\"invoke0\"," +
	"\"file\":\"NativeMethodAccessorImpl.java\",\"line\":-2,\"exact\":false,\"location\":\"?\",\"version\":\"?\"},{\"class\":" +
	"\"jdk.internal.reflect.NativeMethodAccessorImpl\",\"method\":\"invoke\",\"file\":\"NativeMethodAccessorImpl.java\"," +
	"\"line\":62,\"exact\":false,\"location\":\"?\",\"version\":\"?\"},{\"class\":\"jdk.internal.reflect.DelegatingMethodAccessorImpl\"," +
	"\"method\":\"invoke\",\"file\":\"DelegatingMethodAccessorImpl.java\",\"line\":43,\"exact\":false,\"location\":\"?\",\"version\":\"?\"}," +
	"{\"class\":\"java.lang.reflect.Method\",\"method\":\"invoke\",\"file\":\"Method.java\",\"line\":566,\"exact\":false,\"location\":\"?\"," +
	"\"version\":\"?\"},{\"class\":\"com.intellij.rt.execution.application.AppMainV2\",\"method\":\"main\",\"file\":\"AppMainV2.java\",\"line\":131," +
	"\"exact\":true,\"location\":\"idea_rt.jar\",\"version\":\"?\"},{\"class\":\"App\",\"method\":\"main\",\"file\":\"App.java\",\"line\":15,\"exact\":true," +
	"\"location\":\"classes/\",\"version\":\"?\"},{\"class\":\"jdk.internal.reflect.NativeMethodAccessorImpl\",\"method\":\"invoke0\"," +
	"\"file\":\"NativeMethodAccessorImpl.java\",\"line\":-2,\"exact\":false,\"location\":\"?\",\"version\":\"?\"}," +
	"{\"class\":\"jdk.internal.reflect.NativeMethodAccessorImpl\",\"method\":\"invoke\",\"file\":\"NativeMethodAccessorImpl.java\"," +
	"\"line\":62,\"exact\":false,\"location\":\"?\",\"version\":\"?\"},{\"class\":\"jdk.internal.reflect.DelegatingMethodAccessorImpl\"," +
	"\"method\":\"invoke\",\"file\":\"DelegatingMethodAccessorImpl.java\",\"line\":43,\"exact\":false,\"location\":\"?\",\"version\":\"?\"}," +
	"{\"class\":\"java.lang.reflect.Method\",\"method\":\"invoke\",\"file\":\"Method.java\",\"line\":566,\"exact\":false,\"location\":\"?\",\"version\":\"?\"}," +
	"{\"class\":\"com.intellij.rt.execution.application.AppMainV2\",\"method\":\"main\",\"file\":\"AppMainV2.java\",\"line\":131,\"exact\":true," +
	"\"location\":\"idea_rt.jar\",\"version\":\"?\"}]},\"endOfBatch\":false,\"loggerFqcn\":\"org.apache.logging.log4j.spi.AbstractLogger\"," +
	"\"threadId\":1,\"threadPriority\":5,\"service\":\"java-app\"}"
