= Prune Filter

Collecting all logs from a cluster produces a large amount of data, which can be expensive to transport and store. A lot of log data is low-value noise that does not need to be stored.

The prune filter allows for pruning log record fields to reduce the size of logs flowing into a log store.

== Configuring and Using a Prune Filter

A `prune` filter removes fields from each record passing through the filter.

The prune filter extends the filter API by adding a `prune` field and the `in`, and `notIn` fields nested underneath. Both `in` and `notIn` fields are an array of dot-delimited field paths.

=== Definitions:
* `in`: Prune fields from the log record that match paths defined in the array.
* `notIn`: Prune all fields from the log record that do not match paths defined in the array.
* Dot-delimited field path: A path to a field in the log record. It must start with a dot (`.`). The path can contain alpha-numeric characters and underscores `(a-zA-Z0-9_)`. If segments contain characters outside of this range, the segment must be quoted.
** Examples: `.kubernetes.namespace_name`, `.log_type`, `.kubernetes.labels.foobar`, `.kubernetes.labels."foo-bar/baz"`

.Precedence
[NOTE]
`notIn` pruning takes precedence over `in`. If both `in` and `notIn` are specified, vector will first prune all fields *NOT* listed in the `notIn` list, followed by pruning fields specified in the `in` list.

=== Required Fields
The fields `.log_type`, `.log_source` and `.message` *CANNOT* be pruned and are required in all log events.    Additionally, `.hostname` field is also required if the filter is applied to a `GoogleCloudLogging` output.

[IMPORTANT]
If specified, `notIn` *MUST* contain the required fields, and `in` *CANNOT* contain any of the required fields.

=== Example
A configuration specifying a custom prune filter called `my-prune`.

.ClusterLogForwarder
[source,yaml]
----
apiVersion: observability.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: instance 
  namespace: openshift-logging 
spec:
  outputs:
  - name: my-default
    type: http
    http:
      url: https://my-default.foo.bar
  filters:
  - name: my-prune
    type: prune
    prune:
      notIn: [.log_type,.log_source,.message,.kubernetes]
      in: [.kubernetes.container_id,.kubernetes.labels."test-dashes/slashes"]
  pipelines:
  - name: app-prune
    filterRefs:
    - my-prune
    inputRefs:
    - application
    - infrastructure
    outputRefs:
    - my-default
  serviceAccount:
    name: logging-admin
----

== Relevant Links
. link:../../../../api/observability/v1/filter_types.go[API documentation]
. https://issues.redhat.com/browse/LOG-3883[Related JIRA]