apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: cluster-logging-operator
spec:
  channel: ${OPERATOR_PACKAGE_CHANNEL}
  name: cluster-logging
  source: ${CLUSTER_LOGGING_CATALOG}
  sourceNamespace: ${CLUSTER_LOGGING_CATALOG_NAMESPACE}
