# Prometheus Monitor Service (Metrics)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    control-plane: cluster-logging-operator
  name: cluster-logging-operator-metrics-monitor
spec:
  endpoints:
    - port: http-metrics
  namespaceSelector: {}
  selector:
    matchLabels:
      name: cluster-logging-operator
