apiVersion: observability.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: my-forwarder
spec:
  serviceAccount:
    name: my-account
  inputs:
    - name: http-receiver
      type: receiver
      receiver:
        type: http
        port: 8443
        http:
          format: kubeAPIAudit
        tls:
          ca:
            configMapName: my-configmap
            key: ca.crt
          certificate:
            configMapName: my-cert-configmap
            key: cert.crt
          key:
            secretName: my-secret
            key: my.key
          keyPassphrase:
            secretName: my-secret
            key: passphrase
    - name: syslog-receiver
      type: receiver
      receiver:
        type: syslog
        port: 9442
        tls:
          ca:
            configMapName: my-configmap
            key: ca.crt
          certificate:
            configMapName: my-cert-configmap
            key: cert.crt
          key:
            secretName: my-secret
            key: my.key
          keyPassphrase:
            secretName: my-secret
            key: passphrase
  pipelines:
    - name: my-http
      inputRefs:
        - http-receiver
      outputRefs:
        - my-http-output
    - name: my-syslog
      inputRefs:
        - syslog-receiver
      outputRefs:
        - my-sys-out
  outputs:
    - name: my-http-output
      type: http
      http:
        url: http://my-log-output:80
    - name: my-sys-out
      type: syslog
      syslog:
        rfc: RFC5424
        url: tcp://my-syslogservice.example.com:514
