{
 "title": "Openshift Logging",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Elastic Cluster Status",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "max(es_cluster_status)" }
   ]
  },
  {
   "title": "Elastic Nodes",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "topk(1, es_cluster_nodes_number)"
    }
   ]
  },
  {
   "title": "Elastic Shards",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum by(instance)(es_cluster_shards_number{type='active_primary'}))"
    }
   ]
  },
  {
   "title": "Elastic Documents",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by(node)(es_indices_doc_number)"
    }
   ]
  },
  {
   "title": "Total Index Size on Disk",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum by(node)(es_indices_store_size_bytes)"
    }
   ]
  },
  {
   "title": "Elastic Pending Tasks",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(es_cluster_pending_tasks_number)"
    }
   ]
  },
  {
   "title": "Elastic JVM GC time",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(es_jvm_gc_collection_time_seconds[5m]))",
     "legendFormat": "JVM GC time"
    }
   ]
  },
  {
   "title": "Elastic JVM GC Rate",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
   "format": "ops",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(es_jvm_gc_collection_count[5m]))",
     "legendFormat": "JVM heap used"
    }
   ]
  },
  {
   "title": "Queries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Elastic Query/Fetch Latency | Sum",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum by()(rate(es_indices_search_query_time_seconds[5m])) / sum by()(rate(es_indices_search_query_count[5m]))",
       "legendFormat": "query time"
      },
      {
       "expr": "sum by()(rate(es_indices_search_fetch_time_seconds[5m])) / sum by()(rate(es_indices_search_fetch_count[5m]))",
       "legendFormat": "fetch time"
      }
     ]
    },
    {
     "title": "Elastic Query Rate | Top 5",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum by(node)(irate(es_indices_search_query_count[5m]))",
       "legendFormat": "{{node}}"
      }
     ]
    }
   ]
  },
  { "title": "Machine", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "percent", "label": "Percent" }
   ],
   "targets": [
    {
     "expr": "sum by(container)(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{container=~'elasticsearch|fluentd|kibana'})",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Elastic JVM Heap Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "sum(es_jvm_mem_heap_used_bytes)",
     "legendFormat": "JVM heap used"
    }
   ]
  },
  {
   "title": "Elasticsearch Disk Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "percentunit", "label": "Percent" }
   ],
   "targets": [
    {
     "expr": "1 - (es_fs_path_free_bytes / es_fs_path_total_bytes)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "File Descriptors In Use",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short", "label": "Sum" }
   ],
   "targets": [
    {
     "expr": "sum by(app)(label_replace(container_file_descriptors{pod=~'(elastic|kibana|fluentd).+'}, 'app', '$1', 'pod', '([^-]+)-.+'))",
     "legendFormat": "{{app}}"
    }
   ]
  },
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "FluentD emit count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short", "label": "Sum" }
   ],
   "targets": [
    {
     "expr": "sum by (plugin_id)(irate(fluentd_output_status_emit_count{plugin_id!~'object:.+'}[5m]))",
     "legendFormat": "{{plugin_id}}"
    }
   ]
  },
  {
   "title": "FluentD Buffer Availability",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 41 },
   "yaxes": [
    { "format": "percent", "label": "Percent" }
   ],
   "targets": [
    {
     "expr": "100 - max by(plugin_id)(fluentd_output_status_buffer_available_space_ratio)"
    }
   ]
  },
  {
   "title": "Elastic rx bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 41 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(es_transport_rx_bytes_count[5m]))"
    }
   ]
  },
  {
   "title": "Elastic Index Failure Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "ops", "label": "operations/sec" }
   ],
   "targets": [
    {
     "expr": "sum by(node)(irate(es_indices_indexing_index_failed_count[5m]))",
     "legendFormat": "failures"
    }
   ]
  },
  {
   "title": "FluentD Output Error Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 49 },
   "yaxes": [
    { "format": "ops", "label": "operations/sec" }
   ],
   "targets": [
    {
     "expr": "sum by(type)(irate(fluentd_output_status_num_errors{plugin_id!~'object:.+'}[5m]) / irate(fluentd_output_status_write_count{plugin_id!~'object:.+'}[5m]))",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Logs produced(top containers) - Bytes/Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, round(rate(log_logged_bytes_total[5m])))",
     "legendFormat": "namespace: {{namespace}}  podname: {{podname}}"
    }
   ]
  },
  {
   "title": "total bytes produced",
   "type": "row",
   "panels": [
    {
     "title": "Logs produced(top containers) - Bytes",
     "type": "table",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(10, label_replace(label_replace(sum(increase(log_logged_bytes_total[24h])) by (path,  podname), \"znamespace\", \"$1\", \"path\", \".*_(.*)_.*\"), \"zcontainer\", \"$1\", \"path\", \".*_.*_(.*).log\"))"
      }
     ]
    }
   ]
  },
  {
   "title": "Logs collected(top containers) - Bytes/Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, round(rate(log_collected_bytes_total[5m])))",
     "legendFormat": "namespace: {{namespace}}   podname: {{podname}}"
    }
   ]
  },
  {
   "title": "total bytes collected",
   "type": "row",
   "panels": [
    {
     "title": "Logs collected(top containers) - Bytes",
     "type": "table",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(10, label_replace(label_replace(sum(increase(log_collected_bytes_total[24h])) by (path,  podname), \"znamespace\", \"$1\", \"path\", \".*_(.*)_.*\"), \"zcontainer\", \"$1\", \"path\", \".*_.*_(.*).log\"))"
      }
     ]
    }
   ]
  }
 ]
}