apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: cluster-logging
rules:
- apiGroups:
  - config.openshift.io
  resources:
  - infrastructures
  - proxies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - console.openshift.io
  resources:
  - consoleexternalloglinks
  verbs:
  - '*'
- apiGroups:
  - ''
  resources:
  - configmaps
  verbs:
  - '*'
- apiGroups:
  - ''
  resources:
  - namespaces
  - pods
  - services
  - services/finalizers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - oauth.openshift.io
  resources:
  - oauthclients
  verbs:
  - '*'
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - clusterroles
  verbs:
  - '*'
- apiGroups:
  - scheduling.k8s.io
  resources:
  - priorityclasses
  verbs:
  - '*'
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - create
