apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: logging-deployer
rules:
- apiGroups:
    - console.openshift.io
  resources:
    - consoleexternalloglinks
    - consoleplugins
    - consoleplugins/finalizers
  verbs:
    - "*"
- apiGroups:
    - ""
  resources:
    - configmaps
  verbs:
    - "*"
- apiGroups:
    - scheduling.k8s.io
  resources:
    - priorityclasses
  verbs:
    - "*"
- apiGroups:
    - oauth.openshift.io
  resources:
    - oauthclients
  verbs:
    - "*"
- apiGroups:
    - rbac.authorization.k8s.io
  resources:
    - clusterroles
    - clusterrolebindings
  verbs:
    - "*"
- apiGroups:
    - config.openshift.io
  resources:
    - proxies
    - infrastructures
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - security.openshift.io
  resources:
    - securitycontextconstraints
  verbs:
    - create
- apiGroups:
    - ""
  resources:
    - pods
    - namespaces
    - services
    - services/finalizers
  verbs:
    - get
    - list
    - watch
