apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-logging-application-view
rules:
- apiGroups:
  - loki.grafana.com
  resources:
  - application
  resourceNames:
  - logs
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-logging-infrastructure-view
rules:
- apiGroups:
  - loki.grafana.com
  resources:
  - infrastructure
  resourceNames:
  - logs
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-logging-audit-view
rules:
- apiGroups:
  - loki.grafana.com
  resources:
  - audit
  resourceNames:
  - logs
  verbs:
  - get
