apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: loki-tenant-logs
  namespace: openshift-logging
rules:
- apiGroups:
  - 'loki.grafana.com'
  resources:
  - application
  - infrastructure
  - audit
  resourceNames:
  - logs
  verbs:
  - get
  - create
