apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-logging-write-infrastructure-logs
rules:
- apiGroups:
  - loki.grafana.com
  resourceNames:
  - logs
  resources:
  - infrastructure
  verbs:
  - create
