= Forwarding to Amazon Cloudwatch using Web Identities From an STS enabled Cluster

This guide provides a workflow for forwarding to Amazon Cloudwatch in an <<aws-sts, STS>> enabled cluster.

These steps assume that there is a <<setup-sts, STS>> enabled openshift cluster running.

---
== Steps to forward to Cloudwatch using Web Identity

=== Creating a `CredentialsRequest`
. Create a `CredentialsRequest` resource with the appropriate actions.
.. This example `CredentialsRequest` allows creating and describing logs.
+
.aws-cred-request.yaml
[source, yaml]
----
apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  name: my-credrequest # <1>
  namespace: openshift-logging <1>
spec:
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: AWSProviderSpec
    statementEntries:
      - action: # <2>
          - logs:PutLogEvents
          - logs:CreateLogGroup
          - logs:PutRetentionPolicy
          - logs:CreateLogStream
          - logs:DescribeLogGroups
          - logs:DescribeLogStreams
        effect: Allow
        resource: arn:aws:logs:*:*:*
  secretRef:
    name: sts-secret # <3>
    namespace: openshift-logging # <3>
  serviceAccountNames:
    - my-sa # <4>
----
<1> The name and namespace for the credentials request.
<2> The allowed actions for this role.
<3> The name and namespace of the secret containing the generated credentials.
<4> The service account(s) that will use the credentials
+

. Create the role in `AWS` using the <<cco, CCO>> utility.
+
```
$ ccoctl aws create-iam-roles --name=<NAME> --region=<REGION> \ # <1>
  --credentials-requests-dir=<REQ DIR> \ # <2>
  --output-dir=<OUTPUT> \ # <3>
  --identity-provider-arn=arn:aws:iam::<AWS_ACCOUNT_ID>:oidc-provider/<NAME>-oidc.s3.<REGION>.amazonaws.com # <4>
```
<1> The name of the resource along with the region
<2> The credentials request directory where the above `CredentialsRequest` YAML is saved.
<3> The output directory
<4> The identity provider arn
+

. Apply the generated credentials secret.
+
.openshift-logging-sts-secret-credentials.yaml
[source, yaml]
----
apiVersion: v1
stringData:
  credentials: |-
    [default]
    sts_regional_endpoints = regional
    role_arn = <MY ROLE ARN>
    web_identity_token_file = <PATH TO SA TOKEN>
kind: Secret
metadata:
  name: sts-secret
  namespace: openshift-logging
type: Opaque
----
+
```
$ oc apply -f openshift-logging-sts-secret-credentials.yaml
```


=== Configuring a `ClusterLogForwarder`

This example forwarder shows two ways to configure a `cloudwatch` output, with a projected service account token or using a secret containing the service account token.

. Create a `ClusterLogForwarder.yaml`
+
.cluster-log-forwarder.yaml
[source,yaml]
----
apiVersion: observability.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: cw-forwarder # <1>
  namespace: openshift-logging # <1>
spec:
  serviceAccount:
    name: my-sa # <2>
  outputs:
    - name: cw-sa-projected-token
      type: cloudwatch
      cloudwatch:
        groupName: 'cw-projected{.log_type||"missing"}' # <3>
        region: us-west-1
        authentication:
          type: iamRole # <4>
          iamRole:
            roleARN: # <5>
              key: credentials # <5>
              secretName: sts-secret # <5>
            token: # <6>
              from: serviceAccount # <6>
    - name: cw-sa-token-secret
      type: cloudwatch
      cloudwatch:
        groupName: 'cw-token-secret{.kubernetes.namespace_name||.log_type||"missing"}'
        region: us-west-1
        authentication:
          type: iamRole
          iamRole:
            roleARN:
              key: role_arn
              secretName: foo-sts-secret
            token:
              from: secret # <7>
                key: token # <7>
                name: my-sa-token-secret # <7>
  pipelines:
    - name: app-logs
      inputRefs:
        - application
      outputRefs:
        - cw-sa-projected-token
        - cw-sa-token-secret
----
<1> The name and namespace of the forwarder
<2> The service account with the appropriate collection permissions
<3> Group name for the log stream. Can be templated.
<4> The authentication type. For `STS`, use `iamRole`.
<5> The `role_arn` used to authenticate. Specify the name of the secret and the key where the `role_arn` is stored.
<6> The service account token used to authenticate. To use the projected service account token, specify `from: serviceAccount`. 
<7> To use a token from a secret, specify `from: secret` and provide the key and secret name
+

. Apply the configured forwarder.
+
```
$ oc apply -f cluster-log-forwarder.yaml
```

== References
=== Openshift

. [[setup-sts]] https://github.com/openshift/cloud-credential-operator/blob/master/docs/sts.md[Setting up an STS cluster]
. [[cco]] https://github.com/openshift/cloud-credential-operator[Cloud Credential Operator (CCO)]
. https://docs.redhat.com/en/documentation/openshift_container_platform/4.18/html/logging/index[Openshift Logging Documentation]

=== Amazon
. [[aws-sts]] https://docs.aws.amazon.com/STS/latest/APIReference/welcome.html[AWS Security Token Service (STS)]
. 