= Forwarding To Elasticsearch

== Steps to forward to Elasticsearch
. Create a ClusterLogForwarder:
+
----
 oc apply -f cluster-log-forwarder.yaml
----
+
.cluster-log-forwarder.yaml
[source,yaml]
----
kind: ClusterLogForwarder
apiVersion: observability.openshift.io/v1
metadata:
  name: instance
  namespace: openshift-logging
spec:
  outputs:
    - name: external-es
      type: elasticsearch
      elasticsearch:
        url: 'https://example-elasticsearch-secure.com:9200'
        version: 8 <1>
        authentication:
          username:
            key: username
            secretName: es-secret  <2>
          password:
            key: password
            secretName: es-secret  <2>
      tls:
        ca:
          key: ca-bundle.crt      <3>
          secretName: es-secret
        certificate:
          key: tls.crt
          secretName: es-secret   <3>
        key:
          key: tls.key
          secretName: es-secret   <3>
  pipelines:
    - name: my-logs
      inputRefs:
        - application
        - infrastructure
      outputRefs:
        - external-es
----
+
<1> Forwarding to an external Elasticsearch of version 8.x or greater requires the `version` field to be specified otherwise this can be omitted.
<2> Use username and password to authenticate to the server
<3> Enable Mutual Transport Layer Security (mTLS) between collector and elasticsearch, the spec identifies the keys and secret to the respective certificates that they represent.

== Custom Index Configuration

https://docs.openshift.com/container-platform/4.12/logging/log_collection_forwarding/cluster-logging-enabling-json-logging.html[Official Cluster Logging Operator Documentation on JSON Parsing]

A custom index can be configured for elasticsearch by specifying the index field

=== Steps To Configure a Custom Index

. Create a `ClusterLogForwarder` instance to `Elasticsearch`.
* Specify the `index` where to forward messages.
+
----
 oc apply -f cluster-log-forwarder.yaml
----
+
.cluster-log-forwarder.yaml
[source,yaml]
----
kind: ClusterLogForwarder
apiVersion: observability.openshift.io/v1
metadata:
  name: instance
  namespace: openshift-logging
spec:
  outputs:
    - name: external-es
      type: elasticsearch
      elasticsearch:
        url: 'https://example-elasticsearch-secure.com:9200'
        version: 8
        authentication:
          username:
            key: username
            secretName: es-secret
          password:
            key: password
            secretName: es-secret
        index: '{.kubernetes.namespace_name || .log_type || "missing"}' <1>
  pipelines:
    - name: my-logs
      inputRefs:
        - application
        - infrastructure
      outputRefs:
        - external-es
----
+
<1> Use the namespace name for the index or fallback to the log type
