=== Steps to forward to Elasticsearch


. Create a ClusterLogging instance with collection `type: vector`:
+
----
 oc apply -f cluster-logging.yaml
----
+
.cluster-logging.yaml
[source,yaml]
----
kind: ClusterLogging
apiVersion: logging.openshift.io/v1
metadata:
  name: instance
  namespace: openshift-logging
spec:
  collection:
    type: vector
----

. Create a ClusterLogForwarder instance to Elasticsearch.
+
----
 oc apply -f cluster-log-forwarder.yaml
----
+
.cluster-log-forwarder.yaml
[source,yaml]
----
kind: ClusterLogForwarder
apiVersion: logging.openshift.io/v1
metadata:
  name: instance
  namespace: openshift-logging
spec:
  outputs:
    - name: external-es
      type: elasticsearch
      elasticsearch:
        version: 8 <1>
      secret:
        name: es-secret <2>
      url: 'https://example-elasticsearch-secure.com:9200'
  pipelines:
    - name: my-logs
      inputRefs:
        - application
        - infrastructure
      outputRefs:
        - external-es
----
+
<1> Forwarding to an external Elasticsearch of version 8.x or greater requires the `version` field to be specified otherwise this can be omitted. The `version` field is nested under `elasticsearch`.
<2> For a `https` prefix, specify the name of the secret required by the endpoint for TLS communication. If the certificate is signed by `custom root ca`, it must have key: `ca-bundle.crt`. If you want to enable Mutual Transport Layer Security (mTLS) between collector and elasticsearch, the secret must have keys of: `tls.crt`, `tls.key` that point to the respective certificates that they represent. Otherwise, for `http` and `https` prefixes, you can specify a secret that contains a username and password.
