= OTLP Output

The OTLP output forwards logs using HTTP/JSON as defined by the OpenTelemetry Observability Framework.
This is a configuration guide for the `ClusterLogForwarder` spec introduced to send logs to OTLP receivers.


*OTLP* describes the *protocol* for encoding, transporting, and delivering telemetry data between sources using the
https://opentelemetry.io/docs/specs/otlp/[OpenTelemetry OTLP Specification]

.Technical Preview
This feature is tech-preview and an annotation is required to enable it
----
observability.openshift.io/tech-preview-otlp-output: "enabled"
----

---
== Configuring the Forwarder
A new output type `otlp` has been defined in the `ClusterLogForwarder`

.ClusterLogForwarder
[source,yaml]
----
apiVersion: observability.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: my-logforwarder
  namespace: my-app-namespace
  annotations:
    observability.openshift.io/tech-preview-otlp-output: "enabled"  # <1>
spec:
  serviceAccount:
    name: logger-admin
  outputs:
    - type: otlp  # <2>
      name: otel-collector
      otlp:
        url: 'http://my-otel-receiver-service:4318/v1/logs'  # <3>
        authentication:
          token:
            from: serviceAccount  # <4>
        tuning:
          compression: gzip  # <5>
      tls:
        insecureSkipVerify: true  # <6>
  pipelines:
    - name: my-pipeline
      inputRefs:
        - application
        - infrastructure
      outputRefs:
        - otel-collector

----
. Tech preview `annotation` must be enabled
. `type` is '*otlp*'
. `otlp` `url` specify a valid host:port of the otel receiver and *MAY* require termination with "*/v1/logs*" depending upon the configuration of the server
. `otlp` `authentication` is optional and specifies a `token.from` and a value of '*serviceAccount*'
.. The token can also be read from a secret
.. Also available with `username` and `password` authentication spec (refer to HTTP Auth Specification for full scope)
. `otlp` `tuning` is optional and includes standard http tuning options in addition to `compression`: '*gzip*'.
. `tls` includes the standard certificate configuration or specify `insecureSkipVerify`: '*true*'


.TLS InsecureSkipVerify
NOTE: This option is *NOT* recommended for production configurations. If true, the client will be configured to skip validating server certificates.

.API Details for _observability.openshift.io/v1_
* https://github.com/openshift/cluster-logging-operator/blob/master/api/observability/v1/clusterlogforwarder_types.go#L261[TLS Spec]
* https://github.com/openshift/cluster-logging-operator/blob/master/api/observability/v1/output_types.go#L242[HTTP Auth Spec]
* https://github.com/openshift/cluster-logging-operator/blob/master/api/observability/v1/output_types.go#L201[HTTP Tuning Spec]
* https://github.com/openshift/cluster-logging-operator/blob/master/api/observability/v1/output_types.go#L1225[OTLP Tuning Spec]


== Data Model

=== Semantic Convention
The Semantic Conventions in OpenTelemetry (OTel) define a *Resource* as an immutable representation of the entity producing telemetry as *Attributes*.

All *Attributes* are included in the *Resource* object. For example, a process producing telemetry that is running in a container has a container_name,
a cluster_id, a pod_name, a namespace, and possibly a deployment or app_name.

The grouping and reducing of common resource attributes is a key aspect of sending logs via OpenTelemetry.

.Cluster Logging Reference Docs
* https://github.com/rhobs/observability-data-model/blob/main/cluster-logging.md[OTel Data Model]
* https://github.com/openshift/enhancements/blob/master/enhancements/cluster-logging/cluster-logging-otel-support.md[OTel Enhancement Doc]
* https://github.com/openshift/cluster-logging-operator/blob/master/docs/reference/datamodels/viaq/v1.adoc[ViaQ Data Model]
* https://github.com/openshift/cluster-logging-operator/tree/master/hack/logsamples[Example Logs]

.OTel References
* https://opentelemetry.io/docs/specs/otlp/[OTLP Specification]
* https://opentelemetry.io/docs/specs/semconv/[Semantic Conventions]
* https://opentelemetry.io/docs/specs/otel/logs/data-model/[OTel Logs Data Model]
* https://opentelemetry.io/docs/specs/semconv/general/logs/[General Logs Attributes]
