apiVersion: "logging.openshift.io/v1alpha1"
kind: "LogFileMetricExporter"
metadata:
  name: "cluster-log-metrics" # Name must be 'instance'
  namespace: "openshift-logging"
spec:
  resources:
    limits:
      cpu: "100m"
    requests:
      cpu: "100m"
      memory: "128Mi"
  