apiVersion: "logging.openshift.io/v1"
kind: "ClusterLogging"
metadata:
  name: "asdf"
spec:
  managementState: "Managed"
  logStore:
    type: "elasticsearch"
    elasticsearch:
      nodeCount: 1
      storage: {}
      redundancyPolicy: "ZeroRedundancy"
  visualization:
    type: "kibana"
    kibana:
      replicas: 1
  collection:
    type: "fluentd"