////
:_mod-docs-content-type: ASSEMBLY
include::_attributes/common-attributes.adoc[]
include::_attributes/attributes-openshift-dedicated.adoc[]
[id="logging-6-x-reference"]
= 6.x logging API reference
:context: logging-6-x-reference

toc::[]
////

////
** This reference is generated from the content in the openshift/cluster-logging-operator repository.
** Do not modify the content here manually except for the metadata and section IDs - changes to the content should be made in the source code.
////

[id="logging-6-x-reference-LogFileMetricExporter"]
== LogFileMetricExporter

A Log File Metric Exporter instance. LogFileMetricExporter is the Schema for the logFileMetricExporters API

[options="header"]
|======================
|Property|Type|Description

|spec|object|  
|status|object|  
|======================

=== .spec

LogFileMetricExporterSpec defines the desired state of LogFileMetricExporter

Type:: object

[options="header"]
|======================
|Property|Type|Description

|networkPolicy|object|  *(optional)* Define the Network Policy for the LogFileMetricExporter
|nodeSelector|object|  *(optional)* Define which Nodes the Pods are scheduled on.
|resources|object|  *(optional)* The resource requirements for the LogFileMetricExporter
|tolerations|array|  *(optional)* Define the tolerations the Pods will accept
|======================

=== .spec.networkPolicy

Type:: object

[options="header"]
|======================
|Property|Type|Description

|ruleSet|string|  NetworkPolicyRuleSetType is the type of network policy rule set to use

|======================

=== .spec.nodeSelector

Type:: object

=== .spec.resources

Type:: object

[options="header"]
|======================
|Property|Type|Description

|claims|array|  *(optional)* Claims lists the names of resources, defined in spec.resourceClaims,
that are used by this container.

This is an alpha field and requires enabling the
DynamicResourceAllocation feature gate.

This field is immutable. It can only be set for containers.

|limits|object|  *(optional)* Limits describes the maximum amount of compute resources allowed.
More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
|requests|object|  *(optional)* Requests describes the minimum amount of compute resources required.
If Requests is omitted for a container, it defaults to Limits if that is explicitly specified,
otherwise to an implementation-defined value. Requests cannot exceed Limits.
More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
|======================

=== .spec.resources.claims[]

Type:: array

[options="header"]
|======================
|Property|Type|Description

|name|string|  Name must match the name of one entry in pod.spec.resourceClaims of
the Pod where this field is used. It makes that resource available
inside a container.
|request|string|  *(optional)* Request is the name chosen for a request in the referenced claim.
If empty, everything from the claim is made available, otherwise
only the result of this request.

|======================

=== .spec.resources.limits

Type:: object

=== .spec.resources.requests

Type:: object

=== .spec.tolerations[]

Type:: array

[options="header"]
|======================
|Property|Type|Description

|effect|string|  *(optional)* Effect indicates the taint effect to match. Empty means match all taint effects.
When specified, allowed values are NoSchedule, PreferNoSchedule and NoExecute.
|key|string|  *(optional)* Key is the taint key that the toleration applies to. Empty means match all taint keys.
If the key is empty, operator must be Exists; this combination means to match all values and all keys.
|operator|string|  *(optional)* Operator represents a key&#39;s relationship to the value.
Valid operators are Exists and Equal. Defaults to Equal.
Exists is equivalent to wildcard for value, so that a pod can
tolerate all taints of a particular category.
|tolerationSeconds|int|  *(optional)* TolerationSeconds represents the period of time the toleration (which must be
of effect NoExecute, otherwise this field is ignored) tolerates the taint. By default,
it is not set, which means tolerate the taint forever (do not evict). Zero and
negative values will be treated as 0 (evict immediately) by the system.
|value|string|  *(optional)* Value is the taint value the toleration matches to.
If the operator is Exists, the value should be empty, otherwise just a regular string.
|======================

=== .spec.tolerations[].tolerationSeconds

Type:: int

=== .status

LogFileMetricExporterStatus defines the observed state of LogFileMetricExporter

Type:: object

[options="header"]
|======================
|Property|Type|Description

|conditions|array|  Conditions of the Log File Metrics Exporter.
|======================

=== .status.conditions[]

Type:: array

[options="header"]
|======================
|Property|Type|Description

|lastTransitionTime|string|  lastTransitionTime is the last time the condition transitioned from one status to another.
This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
|message|string|  message is a human readable message indicating details about the transition.
This may be an empty string.
|observedGeneration|int|  *(optional)* observedGeneration represents the .metadata.generation that the condition was set based upon.
For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
with respect to the current state of the instance.
|reason|string|  reason contains a programmatic identifier indicating the reason for the condition&#39;s last transition.
Producers of specific condition types may define expected values and meanings for this field,
and whether the values are considered a guaranteed API.
The value should be a CamelCase string.
This field may not be empty.
|status|string|  status of the condition, one of True, False, Unknown.
|type|string|  type of condition in CamelCase or in foo.example.com/CamelCase.
---
Many .condition.type values are consistent across resources like Available, but because arbitrary conditions can be
useful (see .node.status.conditions), the ability to deconflict is important.
The regex it matches is (dns1123SubdomainFmt/)?(qualifiedNameFmt)
|======================

