apiVersion: observability.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: logging
  namespace: openshift-logging
spec:
  serviceAccount:
    name: log-collector
  outputs:
  - name: logging-loki
    type: lokiStack
    lokiStack:
      authentication:
        token:
          from: serviceAccount
      target:
        name: logging-loki
    tls:
      ca:
        key: service-ca.crt
        configMapName: openshift-service-ca.crt
  pipelines:
  - name: logs-to-loki
    inputRefs:
    - application
    - infrastructure
    outputRefs:
    - logging-loki
