#!/bin/bash
source "$(dirname $0)/utils"
assert_resources_exist(){
	# verify deployments -- kibana, curator
	try_until_success "oc -n $NAMESPACE get deployment kibana" ${TIMEOUT_MIN}	

	# verify cron
	try_until_success "oc -n $NAMESPACE get cronjob curator" ${TIMEOUT_MIN}

	# verify DS
	try_until_success "oc -n $NAMESPACE get ds fluentd" ${TIMEOUT_MIN}

	# verify ER
	try_until_success "oc -n $NAMESPACE get elasticsearch elasticsearch" ${TIMEOUT_MIN}

}