apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../base

patches:
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env
      value:
        - name: LOGS_PER_SECOND
          value: "1"
        - name: PAYLOAD_SIZE
          value: "1024"
  target:
    kind: Deployment