apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      app.kubernetes.io/name: dynamic
      app.kubernetes.io/component: dynamic
      app.kubernetes.io/part-of: cluster-logging
    includeSelectors: true
    includeTemplates: true
resources:
  - manifest.yaml