apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

patches:
- patch: |-
    - op: replace
      path: /spec/pipelines/0/outputRefs/0
      value: dynamic-receiver
    - op: add
      path: /spec/outputs
      value:
      - name: dynamic-receiver
        type: http
        http:
          url: http://dynamic-receiver.openshift-logging.svc:8080
  target:
    kind: ClusterLogForwarder