apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      app.kubernetes.io/name: syslog
      app.kubernetes.io/component: receiver
      app.kubernetes.io/part-of: cluster-logging
    includeSelectors: true
    includeTemplates: true

resources:
- ../base
- configmap.yaml
- deployment.yaml
- service_nodeport.yaml