apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: collectors.logging.openshift.io
spec:
  group: logging.openshift.io
  names:
    kind: Collector
    listKind: CollectorList
    plural: collectors
    singular: collector
  scope: Namespaced
  version: v1alpha1
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
          description: Specification for log collector
          properties:
            type:
              description: The type of Log Collection to configure
              type: string
              enum:
              - promtail
            resources:
              type: object
              description: The resource requirements for Fluentd
              properties:
                limits:
                  type: object
                  description: 'Limits describes the maximum amount of compute
                    resources allowed. More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/'
                requests:
                  type: object
                  description: 'Requests describes the minimum amount of compute
                    resources required. If Requests is omitted for a container,
                    it defaults to Limits if that is explicitly specified, otherwise
                    to an implementation-defined value. More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/'
            nodeSelector:
              type: object
              description: Define which Nodes the Pods are scheduled on.
          required:
          - type
  subresources:
    status: {}
