apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: logforwardings.logging.openshift.io
spec:
  group: logging.openshift.io
  names:
    kind: LogForwarding
    listKind: LogForwardingList
    plural: logforwardings
    singular: logforwarding
  scope: Namespaced
  version: v1alpha1
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
          description: Specification for logforwarding of messages
          properties:
            outputs:
              description: Destinations for log messages
              items:
                description: An individual entry for a specific output
                properties:
                  type:
                    description: The output type (e.g. elasticsearch or logstore)
                    type: string
                    enum:
                      - elasticsearch
                      - forward
                      - syslog
                  name: 
                    description: The name of the output
                    type: string
                  endpoint:
                    description: the url to the the service defined by this output
                    type: string
                  secret:
                    properties:
                      name:
                        description: The name of a secret to mount into the collector to use when shipping logs
                        type: string
                    required:
                      - name
                    type: object
              required:
              - type
              - name
              - endpoint
              type: array
            pipelines:
              description: The mapping of sources to outputs
              items:
                properties:
                  name:
                    description: The name of the pipeline
                    type: string
                  outputRefs:
                    description: The name of outputs to send the source logs
                    items:
                      type: string
                    type: array
                  inputType:
                    description: The log source type
                    type: string
                    enum:
                      - logs-app
                      - logs-infra
                      - logs-audit
              required:
              - name
              - source
              - outputRefs
              type: array
          required:
          - outputs
          - pipelines
  subresources:
    status: {}

