apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: logforwardings.logging.openshift.io
spec:
  group: logging.openshift.io
  names:
    kind: LogForwarding
    listKind: LogForwardingList
    plural: logforwardings
    singular: logforwarding
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: Specification of desired state for LogForwarding.
          properties:
            disableDefaultForwarding:
              description: Disable forwarding to the default log store.
              type: boolean
            outputs:
              description: Destinations for log messages
              items:
                properties:
                  endpoint:
                    description: The url to the the service defined by this output
                    type: string
                  name:
                    description: The name of the output
                    type: string
                  secret:
                    description: Secret used to authenticate with the endpoint.
                    properties:
                      name:
                        description: The name of a secret to mount into the collector
                          to use when shipping logs
                        type: string
                    required:
                    - name
                    type: object
                  type:
                    description: The output type (e.g. elasticsearch or logstore)
                    enum:
                    - elasticsearch
                    - forward
                    - syslog
                    type: string
                required:
                - endpoint
                - name
                - type
                type: object
              type: array
            pipelines:
              description: The mapping of sources to outputs
              items:
                properties:
                  inputSource:
                    description: LogSourceType is an explicitly defined log source
                    enum:
                    - logs-app
                    - logs-infra
                    - logs-audit
                    type: string
                  name:
                    description: The name of the pipeline
                    type: string
                  outputRefs:
                    description: The name of outputs to send the source logs
                    items:
                      type: string
                    type: array
                required:
                - inputSource
                - name
                - outputRefs
                type: object
              type: array
          required:
          - outputs
          - pipelines
          type: object
        status:
          description: Observed state of LogForwarding.
          properties:
            lastUpdated:
              description: LastUpdated represents the last time that the status was
                updated.
              format: date-time
              type: string
            message:
              description: Reason is a one-word CamelCase reason for the condition's
                last transition.
              type: string
            outputs:
              description: Outputs is the status of the outputs
              items:
                description: OutputStatus of a given output
                properties:
                  conditions:
                    description: Reasons for the state of the corresponding pipeline
                      for this status
                    items:
                      properties:
                        message:
                          type: string
                        reason:
                          description: OutputConditionReason provides a reason for
                            the given state
                          type: string
                        status:
                          type: string
                        type:
                          type: string
                      type: object
                    type: array
                  lastUpdated:
                    description: LastUpdated represents the last time that the status
                      was updated.
                    format: date-time
                    type: string
                  message:
                    description: Message about the corresponding output
                    type: string
                  name:
                    description: Name of the corresponding output for this status
                    type: string
                  reason:
                    description: Reasons for the state of the corresponding output
                      for this status
                    type: string
                  state:
                    description: State of the corresponding output for this status
                    type: string
                type: object
              type: array
            pipelines:
              description: Pipelines is the status of the outputs
              items:
                description: PipelineStatus is the status of a give pipeline
                properties:
                  conditions:
                    description: Reasons for the state of the corresponding pipeline
                      for this status
                    items:
                      properties:
                        message:
                          type: string
                        reason:
                          type: string
                        status:
                          type: string
                        typ:
                          type: string
                      type: object
                    type: array
                  lastUpdated:
                    description: LastUpdated represents the last time that the status
                      was updated.
                    format: date-time
                    type: string
                  message:
                    type: string
                  name:
                    description: Name of the corresponding pipeline for this status
                    type: string
                  reason:
                    type: string
                  state:
                    description: State of the corresponding pipeline for this status
                    type: string
                type: object
              type: array
            reason:
              description: Reason is a one-word CamelCase reason for the condition's
                last transition.
              type: string
            sources:
              description: LogSources lists the configured log sources
              items:
                description: LogSourceType is an explicitly defined log source
                enum:
                - logs-app
                - logs-infra
                - logs-audit
                type: string
              type: array
            state:
              description: State is the current state of LogForwarding instance
              type: string
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
