apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openshift-logging
labels:
- pairs:
    app.kubernetes.io/name: garage
  includeSelectors: true
resources:
- statefulset.yaml
- service.yaml
- servicemonitor.yaml
- prometheus-rbac.yaml
- storage-secret.yaml
configMapGenerator:
- name: garage-config
  files:
  - config/garage.toml
