apiVersion: v1
kind: Service
metadata:
  name: garage
spec:
  ports:
  - name: s3-api
    port: 3900
    protocol: TCP
    targetPort: 3900
  - name: rpc
    port: 3901
    protocol: TCP
    targetPort: 3901
  - name: s3-web
    port: 3902
    protocol: TCP
    targetPort: 3902
  - name: admin
    port: 3903
    protocol: TCP
    targetPort: 3903
  type: ClusterIP
