apiVersion: v1
kind: Secret
metadata:
  name: test
stringData:
  endpoint: http://garage.openshift-logging.svc:3900
  bucketnames: loki
  access_key_id: GKgarageaccesskey0000
  access_key_secret: garagesecretkey1234567890abcdefgh
  region: garage
type: Opaque
