#!/bin/bash

source ./common

# Expect base collection path as an argument
BASE_COLLECTION_PATH=$1

# Use PWD as base path if no argument is passed
if [ "${BASE_COLLECTION_PATH}" = "" ]; then
    BASE_COLLECTION_PATH=$(pwd)
fi

NAMESPACE="openshift-operators-redhat"

CLO_COLLECTION_PATH="$BASE_COLLECTION_PATH/cluster-logging"
eo_folder="$CLO_COLLECTION_PATH/eo"

echo "Gathering data for elasticsearch-operator"
mkdir -p "$eo_folder"

pods=$(oc -n $NAMESPACE get pods -l name=elasticsearch-operator -o jsonpath={.items[*].metadata.name})
for pod in $pods
do
    get_env $pod $eo_folder $NAMESPACE "Dockerfile-*operator*"
done

oc -n $NAMESPACE get deployment elasticsearch-operator -o yaml > $eo_folder/deployment

csv_name="$(oc -n $NAMESPACE get csv -o name | grep 'elasticsearch-operator')"
oc -n $NAMESPACE get "${csv_name}" -o yaml > "${eo_folder}/csv"