resources:
- logging.openshift.io_clusterlogforwarders.yaml
- logging.openshift.io_clusterloggings.yaml
patchesJson6902:
- path: crd-v1-singleton-patch.yaml
  target:
    group: apiextensions.k8s.io
    version: v1
    kind: CustomResourceDefinition
    name: clusterlogforwarders.logging.openshift.io
- path: crd-v1-clusterloggings-patches.yaml
  target:
    group: apiextensions.k8s.io
    version: v1
    kind: CustomResourceDefinition
    name: clusterloggings.logging.openshift.io
