apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- clusterrolebindings.yaml

namespace: openshift-logging

patches:
- patch: |-
    - op: replace
      path: /spec/pipelines/0/outputRefs/0
      value: loki-stack
  target:
    kind: ClusterLogForwarder
- patch: |-
    apiVersion: "observability.openshift.io/v1"
    kind: ClusterLogForwarder
    metadata:
      name: collector
      namespace: openshift-logging
    spec:
      outputs:
      - name: loki-stack
        type: lokiStack
        lokiStack:
          authentication:
            token:
              from: serviceAccount
          target:
            namespace: openshift-logging-storage
            name: lokistack-dev
        tls:
          ca:
            key: service-ca.crt
            configMapName: openshift-service-ca.crt
