#!/bin/sh
set -eou pipefail

LOGGING_VERSION=${LOGGING_VERSION:-6.1}

LOGGING_VECTOR_VERSION=${LOGGING_VECTOR_VERSION:-v0.47.0}
LOGGING_LOG_FILE_METRIC_EXPORTER_VERSION=${LOGGING_LOG_FILE_METRIC_EXPORTER_VERSION:-6.1}

LOGGING_IS=${LOGGING_IS:-openshift-logging}
export IMAGE_CLUSTER_LOGGING_OPERATOR_REGISTRY=${IMAGE_CLUSTER_LOGGING_OPERATOR_REGISTRY:-quay.io/${LOGGING_IS}/cluster-logging-operator-registry:${LOGGING_VERSION}}
export IMAGE_CLUSTER_LOGGING_OPERATOR=${IMAGE_CLUSTER_LOGGING_OPERATOR:-quay.io/${LOGGING_IS}/cluster-logging-operator:${LOGGING_VERSION}}
export IMAGE_LOGGING_VECTOR=${IMAGE_LOGGING_VECTOR:-quay.io/${LOGGING_IS}/vector:${LOGGING_VECTOR_VERSION}}
export IMAGE_LOG_FILE_METRIC_EXPORTER=${IMAGE_LOG_FILE_METRIC_EXPORTER:-quay.io/${LOGGING_IS}/log-file-metric-exporter:${LOGGING_LOG_FILE_METRIC_EXPORTER_VERSION}}

export CLUSTER_LOGGING_OPERATOR_NAMESPACE=${CLUSTER_LOGGING_OPERATOR_NAMESPACE:-openshift-logging}
export CLUSTER_LOGGING_CATALOG=${CLUSTER_LOGGING_CATALOG_NAME:-cluster-logging-catalog}
export CLUSTER_LOGGING_CATALOG_NAMESPACE=${CLUSTER_LOGGING_CATALOG_NAMESPACE:-${CLUSTER_LOGGING_OPERATOR_NAMESPACE}}
