#!/bin/sh
set -eou pipefail

LOGGING_VERSION=${LOGGING_VERSION:-6.0}

LOGGING_VECTOR_VERSION=${LOGGING_VECTOR_VERSION:-6.0}
LOGGING_LOG_FILE_METRIC_EXPORTER_VERSION=${LOGGING_LOG_FILE_METRIC_EXPORTER_VERSION:-6.0}
LOGGING_CONSOLE_PLUGIN_VERSION=${LOGGING_CONSOLE_PLUGIN_VERSION:-5.9}
LOGGING_CONSOLE_PLUGIN_VERSION=${LOGGING_CONSOLE_PLUGIN_VERSION:-6.0}

LOGGING_IS=${LOGGING_IS:-openshift-logging}
export IMAGE_CLUSTER_LOGGING_OPERATOR_REGISTRY=${IMAGE_CLUSTER_LOGGING_OPERATOR_REGISTRY:-quay.io/${LOGGING_IS}/cluster-logging-operator-registry:${LOGGING_VERSION}}
export IMAGE_CLUSTER_LOGGING_OPERATOR=${IMAGE_CLUSTER_LOGGING_OPERATOR:-quay.io/${LOGGING_IS}/cluster-logging-operator:${LOGGING_VERSION}}
export IMAGE_LOGGING_VECTOR=${IMAGE_LOGGING_VECTOR:-quay.io/${LOGGING_IS}/vector:${LOGGING_VECTOR_VERSION}}
export IMAGE_LOG_FILE_METRIC_EXPORTER=${IMAGE_LOG_FILE_METRIC_EXPORTER:-quay.io/${LOGGING_IS}/log-file-metric-exporter:${LOGGING_LOG_FILE_METRIC_EXPORTER_VERSION}}
export IMAGE_LOGGING_CONSOLE_PLUGIN=${IMAGE_LOGGING_CONSOLE_PLUGIN:-quay.io/openshift-logging/logging-view-plugin:${LOGGING_CONSOLE_PLUGIN_VERSION}}

export CLUSTER_LOGGING_OPERATOR_NAMESPACE=${CLUSTER_LOGGING_OPERATOR_NAMESPACE:-openshift-logging}
