name: Spell checking

on:
  pull_request_target:
    branches:
      - "**"
    types:
      - opened
      - reopened
      - synchronize

permissions:
  contents: read

jobs:
  spelling:
    name: Spell checking
    permissions:
      contents: read
      pull-requests: read
    runs-on: ubuntu-latest
    concurrency:
      group: spelling-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Spell Check
        uses: crate-ci/typos@v1.33.1
        continue-on-error: true
        with:
          config: .github/actions/spelling/_typos.toml
