set -eou pipefail
export LOKI_OPERATOR_CATALOG="${LOKI_OPERATOR_CATALOG:-redhat-operators}"
export LOKI_OPERATOR_CATALOG_IMAGE="${LOKI_OPERATOR_CATALOG_IMAGE:-}"
export LOKI_OPERATOR_CATALOG_NAMESPACE="${LOKI_OPERATOR_CATALOG_NAMESPACE:-openshift-marketplace}"
export LOKI_OPERATOR_NAMESPACE="${LOKI_OPERATOR_NAMESPACE:-openshift-operators-redhat}"
export OPERATOR_PACKAGE_CHANNEL="${OPERATOR_PACKAGE_CHANNEL:-stable-6.4}"
